### ISSUE TITLE
zos.json file shows incorrect zos version number.

### ISSUE THREAD

**Issue by crazyrabbitLTC** [zeppelinos/zos#1008]
The current release candidate for `zos 2.4` when running `zos init` (or in case of a local install `npx zos init`) the zos.json file registers `zos` version as `2.2`. 

Expected Behavior: Unless the `zos.json` files' entry for `"zosversion"` is not intended to match the `zos version` we are using, I would expect the version to be indentical to the actual `zos version` I am creating the project with.

**Comment by crazyrabbitLTC** [comment]
I'm going to assume maybe the issue is here: 

https://github.com/zeppelinos/zos/blob/master/packages/cli/src/models/files/ZosVersion.ts

Line 4? The `zos version` number seems to be hardcoded to 2.2 :-)

**Comment by spalladino** [comment]
> Unless the zos.json files' entry for "zosversion" is not intended to match the zos version we are using,

That's the catch. zosversion is actually not the version of zos, but that of the config file. We are renaming it to manifestVersion in 2.5 to prevent this confusion!
