### ISSUE TITLE
zos transfer command hangs (and freezes terminal) zos 2.4.0-rc.3

### ISSUE THREAD

**Issue by crazyrabbitLTC** [zeppelinos/zos#1025]
On my machine using the `zos transfer` command locks up my terminal. It's not possible to even escape out of the node process, I need to manually close the terminal window. 

Expected Behavior:

I expect to be able to use `zos transfer` to send funds from one address to another. 

Encountered Behavior: 

When calling `zos transfer` I am prompted to choose my network, I choose development (I have ganache running on the proper port). Then I am prompted to choose an address to send from. However at this point, the terminal is frozen and I am not able to proceed further.  The screenshot shows exactly the point. 

I need to manually close the terminal window, no other action seems to unlock the terminal.

<img width="513" alt="Screen Shot 2019-06-20 at 4 11 00 PM" src="https://user-images.githubusercontent.com/1938013/59878521-83e8b200-9376-11e9-8df1-a57a12fe4916.png">

**Comment by jcarpanelli** [comment]
This is somewhat bizarre. I was experiencing exactly the same issue when using `zos` globally, but I fixed it after uninstalling and reinstalling both `zos` and `zos-lib`. Also, It seems to be working without issues when installed as a dev dependency.

Could you please try uninstalling and reinstalling them?
