### ISSUE TITLE
zos status command is listed as an available command but has been removed.  zos 2.4.0-rc.3

### ISSUE THREAD

**Issue by crazyrabbitLTC** [zeppelinos/zos#1026]
When typing `zos` the console lists the complete list of command available. One of these commands is `zos status`, however when attempting to use this command, `zos` returns `Status command has been removed.`

<img width="488" alt="Screen Shot 2019-06-20 at 4 18 18 PM" src="https://user-images.githubusercontent.com/1938013/59878734-0b362580-9377-11e9-9768-f10a1d6e568f.png">

**Comment by jcarpanelli** [comment]
I think the best thing to do here is just remove the `commands/status.ts` file. Will create a PR with it :)

**Comment by spalladino** [comment]
If it's possible to keep it callable so we display the "sorry, it was removed" notice, but not display it on the help, great. If not, let's remove it from everywhere!

**Comment by spalladino** [comment]
@jcarpanelli perhaps we can remove the command object, but add some custom handler to commander for when the user inputs `status`?

**Comment by spalladino** [comment]
Fixed in #1032
