### ISSUE TITLE
zos update didn't asked for init function neither it can be called later with send-tx

### ISSUE THREAD

**Issue by ylv-io** [zeppelinos/zos#1028]
![image](https://user-images.githubusercontent.com/3285000/59878525-33db1100-93b1-11e9-9816-75bf2a3cb820.png)

To my understanding `update` command should provide a way to call init method. Also I was unable to call init method later with `send-tx`. Is it by design?

**Comment by crazyrabbitLTC** [comment]
It's not possible to call the initializer more than once, that includes when you update. The initializer has already been called and can't be called again. You can only add new functions you want to call if you want to set some sort of new deployment state. However I think, the modifier (I might be wrong) can still be used just once.

**Comment by ylv-io** [comment]
Yeah. You are right. I am closing the issue.

**Comment by jcarpanelli** [comment]
You are right @crazyrabbitLTC. The best thing to do here would be to check if an initializer function has been called before, and don't show the initializer functions it that's the case.
