### ISSUE TITLE
Getting a "Cannot read property 'contracts_build_directory'" error. 

### ISSUE THREAD

**Issue by crazyrabbitLTC** [zeppelinos/zos#1029]
So here is another weird one: 

(yes I have restarted my machine). 

`zos create` and `zos push` are giving me errors. 

This is a zepkit tutorial created via the global `zos unpack tutorial` command. 

<img width="713" alt="Screen Shot 2019-06-20 at 5 05 28 PM" src="https://user-images.githubusercontent.com/1938013/59881497-c3ff6300-937d-11e9-906e-434c86e3ae65.png">

**Comment by spalladino** [comment]
@crazyrabbitLTC we are not being able to reproduce this. Are you trying this on a clean download of the zepkit? Could you try again adding `--verbose`?

**Comment by jcarpanelli** [comment]
Fixed in https://github.com/zeppelinos/zos/pull/1038 :slightly_smiling_face:.
