### ISSUE TITLE
`npx zos` throws: `Cannot read property 'UriResolver' of undefined`

### ISSUE THREAD

**Issue by obernardovieira** [zeppelinos/zos#1046]
This error only happens when running zos locally, like `npx zos init`.
This happens since version 2.2.0

nodejs: v10.15.3
truffle: v5.0.13
solc: v0.5.8

**Comment by jcarpanelli** [comment]
HI @obernardovieira, could you please specify exactly which version of `zos` and `zos-lib` are you currently using?

**Comment by obernardovieira** [comment]
Last time I've used zos locally (with npx) I was in 2.2.0. Usually, I use the global installation (although I only have one at a time). But It happened yesterday with zos and zos-lib in 2.4.0
But then I've tried some previous versions, like 2.2.0 and the same happened.

After writing this above part of the comment I decided to try again. Yesterday I left the version 2.2.2 installed, and it now worked (It wasn't working yesterday) so I updated to 2.4.0 and I've got an error that I've seen yesterday as well `Cannot read property 'UriResolver' of undefined`. Then, downgraded again to 2.2.2 and got the initial error again `zos_lib_1.Logger is not a constructor`.

**Comment by wmitsuda** [comment]
I've just created a new project using zos 2.4 and I'm getting the same error with npx. However, I've copied the yarn.lock file from another existing working project and it works.

I think there is something among the current dependencies that is breaking zos if installing from scratch at this exact moment.

**Comment by wmitsuda** [comment]
Right now, you can reproduce it using these steps:

```shell
npm init -y
yarn add -D zos zos-lib
npx zos
```

You will get the `Cannot read property 'UriResolver' of undefined` error.

**Comment by jcarpanelli** [comment]
@obernardovieira, @wmitsuda  thanks for reporting this :+1:. It seems that this only occurs when installing `zos` and `zos-lib` using yarn. Could you please try installing them using `npm` instead? In the meantime we will dig deeper into this issue and fix it soon!

**Comment by wmitsuda** [comment]
Oh... damn yarn... but ok, I can use a working yarn.lock from another project for now.

**Comment by wmitsuda** [comment]
I've just upgraded to zos 2.4.1 and I do confirm it is now working perfectly with yarn.

**Comment by jcarpanelli** [comment]
Thanks for confirming this @wmitsuda! I'm closing this issue :+1:
