### ISSUE TITLE
zos compile removes networks object from contract.json file

### ISSUE THREAD

**Issue by ylv-io** [zeppelinos/zos#1071]
![image](https://user-images.githubusercontent.com/3285000/60675066-35620a00-9e84-11e9-9b89-3651a48e9b5e.png)
Any code depending on `networks` object in `.json` files would fail. Prime example ZepKit which extracts contract addresses from `networks` object.

**Comment by jcarpanelli** [comment]
My 2 cents here: Maybe the best thing to do in this case is to read the contract from the `zos.network.json`  file (from zepkit) rather than modifying the compiler output and add repeated or not necessary info to it.

**Comment by spalladino** [comment]
I recall there was a script set up by Brendan a while back, which I think
followed an approach similar to the one you're proposing Jota. I'll check
it out and see if it applies!

**Comment by ylv-io** [comment]
Even if we read address from `zos.network.json` our compiler then still would break Truffle Contract Schema which other tools may depend which would make impossible for them to use it.
