### ISSUE TITLE
zos.xxxxx.json not updating after changing proxy admin using set-admin

### ISSUE THREAD

**Issue by buddies2705** [zeppelinos/zos#1072]
When using set-admin, we change ownership of the project using set-admin command, the command output is showing that ownership is changed to a new address but zos.xxxx.json is not reflecting it. It's still showing old owner.

**Comment by ylv-io** [comment]
Hey @buddies2705. Can you share which zos version you've used `zos --version`?

**Comment by buddies2705** [comment]
2.4.0

**Comment by spalladino** [comment]
This is actually ok: `set-admin` changes the owner of the ProxyAdmin, but the admin of each proxy remains the same. The issue is that we are not tracking or checking the owner of the ProxyAdmin anywhere. I created #1106 to handle this.
