### ISSUE TITLE
Doesn't work with yarn workspaces

### ISSUE THREAD

**Issue by PaulRBerg** [zeppelinos/zos#1076]
I cannot use zos within a monorepo maintained with [yarn workspaces](https://yarnpkg.com/lang/en/docs/workspaces/). I'm getting the following error:

> Could not find a zos.json file for 'openzeppelin-eth'. Make sure it is provided by the npm package.

Workspaces is a feature from yarn that aggregates all common node modules at the root of your repo, but I presume zos is only looking for the relative folder, never above.

I also asked about an alternative solution on StackOverflow, but no one answered: https://stackoverflow.com/questions/56910467/when-using-yarn-workspaces-how-to-force-a-package-to-be-installed-in-the-relati

**Comment by jcarpanelli** [comment]
Hey @PaulRBerg! Thanks for raising this. Indeed, `zos` only looks for EVM packages inside the project's `node_modules` folder, so this is probably causing the issue.  We'll check it out :+1:
