### ISSUE TITLE
Enhancement: Add a --version command 

### ISSUE THREAD

**Issue by crazyrabbitLTC** [zeppelinos/zos#1093]
For the sake of standardization would be convenient to have a `--version` command available to tell the user which version they are using.  Maybe a stretch goal would be an `--update` command as well which would run `npm install .....`

**Comment by spalladino** [comment]
Unless I'm missing something, this already exists (at least on version 2.4)

**Comment by jcarpanelli** [comment]
Indeed, the `--version` flag is already being provided by the cli:
```
foo@bar:~$ zos --version
2.4.1
```
Regarding the `--update` flag idea, I think that this might be out of the oz cli's scope, and that that version management should be managed by the package manager.

**Comment by crazyrabbitLTC** [comment]
Yes I was checking it again, it does exist. I'm not sure why it didn't work for me (typo?). 

That said, it's not listed as a command when we type `--help`.

**Comment by spalladino** [comment]
Closing the issue as the command is implemented. I don't think it's necessary to add it to the reference, since most users are familiar with `version` or `--version` in a command line tool.
