### ISSUE TITLE
Inconsistent CLI behavior

### ISSUE THREAD

**Issue by crazyrabbitLTC** [zeppelinos/zos#1098]
Maybe this is my mistake, but is the follow behavior correct? I would expect all commands to work with or without the prepended `--`. 

In this case there is an inconsistency IMHO about how the cli is working. 

![Screen Shot 2019-07-16 at 8 02 33 AM](https://user-images.githubusercontent.com/1938013/61292824-4245fe00-a7a0-11e9-8380-186ba482aba0.png)

**Comment by crazyrabbitLTC** [comment]
This is also when using the new 2.5 `openzeppelin` release candidate with an additional error I'll try to make another issue for. 
![Screen Shot 2019-07-16 at 8 05 24 AM](https://user-images.githubusercontent.com/1938013/61292945-8afdb700-a7a0-11e9-8902-315533a840c9.png)

**Comment by spalladino** [comment]
> I would expect all commands to work with or without the prepended --.

That's not the expected behavior. Command names do not take the `--` prefix, only their option names. `--version` is an exception to the rule, since command-line programs accept either `cmd version` and `cmd --version`, so we accept both.

For example, with git:

```
~$ git version
git version 2.19.1
hub version 2.11.2
~$ git --version
git version 2.19.1
hub version 2.11.2
~$ git status
On branch master
...
~$ git --status
unknown option: --status
```
