### ISSUE TITLE
Lack of manifest tricks 2.5 release candidate in thinking we are using zos 1.x

### ISSUE THREAD

**Issue by crazyrabbitLTC** [zeppelinos/zos#1099]
I have `zos 2.4` installed globally and installed the 2.5 release candidate locally. The project was built using `zos 2.4`.

![Screen Shot 2019-07-16 at 8 07 42 AM](https://user-images.githubusercontent.com/1938013/61293102-ed56b780-a7a0-11e9-89af-b4deb737c1fa.png)

When trying to compile with the 2.5 release candidate I get this error: 

```Manifest version identifier not found in /Users/dennison/Documents/Identity/zos.json. This means the project was built with an older version of openzeppelin (1.x), and needs to be upgraded. Please refer to the documentation at https://docs.zeppelinos.org for more info.``` 

It seems that the lack of manifest version is interpreted as being a `zos 1.x` project, which it is not. There also does not seem to be any information how to correct this.  The version jump from 1.x to 2.x was accompanied by a changelog that promised a migration guide would be created to help users move from 1.x to 2.x. Was this ever created? 
https://github.com/zeppelinos/zos/releases/tag/v2.0.0

**Comment by crazyrabbitLTC** [comment]
For reference my `zos.json` file. Created by `zos 2.4`. 
![Screen Shot 2019-07-16 at 8 11 23 AM](https://user-images.githubusercontent.com/1938013/61293291-576f5c80-a7a1-11e9-952b-c8a434f5f10a.png)

**Comment by jcarpanelli** [comment]
Omg, those bug catcher skills @crazyrabbitLTC :muscle: :bug:.
