### ISSUE TITLE
Incorrect instructions when running "oz init"

### ISSUE THREAD

**Issue by crazyrabbitLTC** [zeppelinos/zos#1108]
<img width="713" alt="Screen Shot 2019-07-16 at 5 18 10 PM" src="https://user-images.githubusercontent.com/1938013/61330528-cecadd80-a7ed-11e9-9ef2-cdd626c00f51.png">

After running `oz init` the cli informs the user to now run `zos create` to continue rather than `oz create`.

**Comment by spalladino** [comment]
Good catch!
