### ISSUE TITLE
Consider indexing name argument in all Vouching events

### ISSUE THREAD

**Issue by tinchoabbate** [zeppelinos/zos#132]
@spalladino [suggested in PR #115](https://github.com/zeppelinos/zos/pull/115#discussion_r219619581) indexing name arguments for all events fired in the `Vouching` contract.

I'm moving the discussion outside the PR so it can be better documented.

Related issues were the problem of indexing string arguments has been discussed:
- [in OpenZeppelin](https://github.com/OpenZeppelin/openzeppelin-solidity/issues/992)
- [in zOS](https://github.com/zeppelinos/zos-lib/issues/199)

**Comment by spalladino** [comment]
Following the discussion in https://github.com/OpenZeppelin/openzeppelin-solidity/issues/992, it'd seem like the best course of action would be to make `name` indexed in all events, and add a `fullname` unindexed argument in `DependencyCreated`. WDYT?

**Comment by tinchoabbate** [comment]
Reviewed the comment you left in the PR, and I've been working locally on a new implementation that addresses them in some ways.

Quick question, do we need the `name` to be a `string`? Could it instead be a `bytes32`? In my tests I'm seeing that (as you mentioned in the PR), `bytes32 indexed` event arguments are not being hashed. Furthermore, it seems that only fixed-size types can be indexed (see https://github.com/trufflesuite/truffle/issues/405#issuecomment-312067312).
