### ISSUE TITLE
Remove placeholder TPL imports from ZepToken

### ISSUE THREAD

**Issue by fiiiu** [zeppelinos/zos#139]
Two [imports](https://github.com/zeppelinos/zos/blob/TPL-integration/packages/vouching/contracts/ZepToken.sol#L7) are made in `ZepToken` exclusively to have Truffle artifacts available. Despite [this](https://github.com/trufflesuite/truffle/issues/1250) being supposedly solved, Truffle is not finding the artifacts in the TPL dependency.

Make sure to remove these when TPL is released as a package.

**Comment by facuspagnuolo** [comment]
Fixed in https://github.com/zeppelinos/zos/commit/cc4eb539642ff5c255d0bece293d004c9dcbef6b
