### ISSUE TITLE
Setup kernel ZeppelinOS app project

### ISSUE THREAD

**Issue by facuspagnuolo** [zeppelinos/zos#154]
This issue depends on https://github.com/zeppelinos/zos/issues/153

The idea is to make [vouching package](https://github.com/zeppelinos/zos/tree/master/packages/vouching) a ZeppelinOS app. We should link this app to the [on-chain version of TPL](https://github.com/zeppelinos/tpl-contracts-zos/) and include the removed `ZepValidator` contract. Given that the audit may not be finished, to start with this issue we will need to publish a pre-release of TPL on NPM.

The contracts to register should be `ZepToken`, `Vouching` and `ZepValidator`. Then, deploy these contracts to some testnet networks (testnet, ropsten, rinkeby and/or kovan) and test that the expected behavior and the integration with TPL work fine.

Note that this project should be working with a beta version of ZeppelinOS to ensure we are using the upcoming version of contracts.

PS: Consider renaming `vouching` to `kernel`

**Comment by ajsantander** [comment]
Addressed by PR #174
