### ISSUE TITLE
Detect incompatible Package versions

### ISSUE THREAD

**Issue by facuspagnuolo** [zeppelinos/zos#159]
Given that we are breaking backward compatibility with the `Package` implementation for the next release, we will need to think a way for the CLI to detect and warn the user in case they try to link to a lib (e.g. OZ-zos 1.9.x) that is backed by a  previous `Package` version.

A possible solution could be to detect usages of old `Package`s with the new version of the CLI, and also provide a patch for `zos@1.9.x` to detect links to libs backed by the new implementation of `Package`.

**Comment by spalladino** [comment]
Will implement via `zosversion` field check in zos.json files as discussed in https://github.com/zeppelinos/zos/issues/131

**Comment by spalladino** [comment]
Fixed in #162 and #163
