### ISSUE TITLE
Question: how will inherit a contract affect the storage order?

### ISSUE THREAD

**Issue by xinbenlv** [zeppelinos/zos#16]
Dear ZOS team,

We (boba.pikt.io) want to upgrade our legacy contract, and one of the task is to change the owner mechanism from our customized version to the Ownable provided by zos, we want to know if that will affect what's being discussed here: https://docs.zeppelinos.org/docs/advanced.html#preserving-the-storage-structure

By the way, please kindly advice if this is the best place to ask question, or should we go to some ZOS-preferred discussion channel?

Thank you !

@xinbenlv

**Comment by spalladino** [comment]
Hey @xinbenlv! That'd depend on how your owner mechanism works today, and whether your contracts today are upgradeable or not. Basically, you need to ensure that all state variables are defined on the same order in the new contract as they were in the old one. So, if you have a custom owner implementation that defines an `address owner` state variable, since zOS version uses the same, you should be fine. Make sure to test it before deploying though!

**Comment by xinbenlv** [comment]
Thanks Santiago,

The question is, if we have the following contracts setup 

```
contract A is Base {
// ------- added before migration 0
  uint varA1;
// ------- added after migration 0
  uint varA2;
}

contract Base {
// ------- added before migration 0
  uint varB1;
// ------- added after migration 1
  uint varB2;
}
```
Would it breaks the requirement for ZOS proxy pattern to work?

**Comment by xinbenlv** [comment]
Thanks, that's what I think the case too. Thank you very much for confirming it. Since the data migration currently is still a very gas-consuming problem, we could either (1) propose to support low gas cross-contract data migration (2) suggest the solidity and its compiler to support memory allocation per inheritance.  Either way it seems to need an EIP Category "Core" proposal? And it seems (1) is better. Shall we bring this to the EIP community to discuss?

@xinbenlv

**Comment by spalladino** [comment]
@xinbenlv I don't think that (1) would get much adoption, as it implies a big change on EVM rules. As for (2), I'm not sure I understand what you mean, could you clarify?

**Comment by facuspagnuolo** [comment]
The main concern of the issue was answered above. Since there was no more activity, we are closing it. If there are any further questions please open a new issue.
