### ISSUE TITLE
Add thorough documentation for lib contracts architecture

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos#18]
As a user peeks into the zos.network.json files, they'll notice these entries with addresses, which are not explained in the documentation. The only info provided today is in the Reference, but there is no explanation at all in the Guides.

Add a chapter or subchapter on these classes, describing the on-chain architecture of a zOS project.

**Comment by facuspagnuolo** [comment]
Consider adding details about the new interface supported by the `Package` contract based the work done in https://github.com/zeppelinos/zos/pull/140

**Comment by ajsantander** [comment]
Addressed by #239
