### ISSUE TITLE
Add tests for ZEPValidator

### ISSUE THREAD

**Issue by ajsantander** [zeppelinos/zos#199]
ZEPValidator is being migrated from https://github.com/TPL-protocol/tpl-contracts/tree/audit into https://github.com/zeppelinos/zos/tree/master/packages/vouching.

The original repo has a test for it at: https://github.com/TPL-protocol/tpl-contracts/blob/audit/scripts/testZEPValidator.js, however, this test in not in the same "Truffle test" format as the rest of the tests in the zos package.

We need to make sure that this test is also migrated and ported into zos.

**Comment by ajsantander** [comment]
Addressed by #211

**Comment by facuspagnuolo** [comment]
Closing this issue since `ZEPValidator` is being kept under `OrganizationsValidator` in https://github.com/TPL-protocol/tpl-contracts-eth.
