### ISSUE TITLE
Review Initializable and Migratable base contracts

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos#2]
The `Migratable` contract from zos-lib is not trivial to use, as there is often confusion around the need of specifying the contract name, or what does the "version" represent. We agreed on reviewing these contracts to see if we could somehow simplify them (they also currently emit a solc compiler warning, at least let's fix that!).

Add a section in the documentation explaining how to use the new contracts. Review the [existing documentation](https://docs.zeppelinos.org/docs/building.html) around the usage of Migratable, change it to use the new versions, and clarify the need for it. Several users believe that it is mandatory to use Migratable for a contract to be used with zOS, increasing the fear of lock-in into the platform, so we need to make sure in the docs that it is not the case.

**Comment by spalladino** [comment]
Once documented, ping https://github.com/zeppelinos/labs/issues/129 to check if the clarification helps solve the issue.

**Comment by frangio** [comment]
@spalladino What solc warning were you referring to?

**Comment by spalladino** [comment]
@frangio I got a report on it, but did not attempt to reproduce it. If it is not present in #12, I'd discard the issue.

**Comment by spalladino** [comment]
Closing via #12
