### ISSUE TITLE
zos not exiting terminal when using HDWalletProvider and Infura

### ISSUE THREAD

**Issue by haraldini** [zeppelinos/zos#20]
Not sure where the issue is in details, but all zos commands exit cleanly when using `--network local.`

Using any infura network thats been setup with `HDWalletProvider` within `truffle.js` is hanging even when executing correctly on the last step and needs to be cancelled manually

For instance
```
[ZosNetworkFile] Successfully written zos.rinkeby.json
0x3a1bc630ce85bda9c63bab2aa....... //stuck here
^C //manual cancel
```

My first though was this was due to writing the file, but even zos status `--network rinkeby` is hanging at the end

**Comment by spalladino** [comment]
That's odd, thanks for the report @haraldini!

**Comment by haraldini** [comment]
Got the same behaviour when using another node with HDWalletProvider, so I don't think its Infura related.

**Comment by spalladino** [comment]
Which version of the HDWalletProvider are you using @haraldini ?

**Comment by haraldini** [comment]
0.0.6, 
It hasn't been updated in 6 month
