### ISSUE TITLE
Address Nomic comments and recommendations to kernel contracts

### ISSUE THREAD

**Issue by facuspagnuolo** [zeppelinos/zos#203]
### [zOS2V-O01]
- [x] Improve ZEPToken-TPL integration tests to ensure that if a recipient's attribute is revoked they cannot receive tokens but can still transfer to other allowed recipients. 
- [x] Add brief inline documentation telling how TPL works for the ZEPToken

### [zOS2V-O02]
- [x]  Update [ZEPToken inline documentation](https://github.com/zeppelinos/zos/blob/b2d3987d32ddf6c5f3291c960d5797291d60c6aa/packages/vouching/contracts/ZEPToken.sol#L10)

### [zOS2V-O03] 
- [x] Use `AddressUtils#isContract` in `Vouching#create`

### [zOS2V-O04] 
- [x] Fix [unvouch test](https://github.com/zeppelinos/zos/blob/c5019dd48153e7dec681a224bc8d328446eafd27/packages/vouching/test/contracts/Vouching.test.js#L220) to work with `stakeAmount.plus(1)` instead.

**Comment by nventuro** [comment]
Closed via #225, #227 and #236.
