### ISSUE TITLE
Consider removing difference between app and lib until publishing

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos#207]
Today a zOS user needs to decide up front whether he'll be using zOS to create a shared lib or an app, and that decision cannot be changed later. 

We can leverage lightweight mode to allow for postponing this decision: initially, all development is in lightweight mode, but we can give our users the chance to `publish` their work as an app or lib (or both) later down the road, based on whether they want their work to be reusable by other teams.

**Comment by spalladino** [comment]
This came up from an idea by @maraoz. After discussing it with @facuspagnuolo, we arrived to the conclusion that an app is currently a strict superset of a lib (except that the app arbitrarily blocks the freeze command).

We could very easily implement this by just dropping the `--lib` flag to the `init` command. This would imply:
- Users do not need to decide whether their project will be a lib or an app when initializing the project.
- Every project will start ligthweight, and switch into full mode upon `publish`ing (we could even drop the need for `push` during lightweight later down the road)
- Partners working on a lib would be able to create proxies to test their own code

On the other hand, we see the following downsides:
- Any proxy created by a lib developer for testing will be included in the zos.network.json, and broadcasted to all consumers of the lib; the CLI will ignore this info though

**Comment by maraoz** [comment]
sounds great!! We can deal with hiding or removing the "unwanted proxies" later in development :)
