### ISSUE TITLE
Add link to documentation on selfdestruct warning

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos#26]
When `add`ing a contract with `selfdestruct`, the CLI raises a warning explaining it is a security risk (see https://github.com/zeppelinos/zos-cli/pull/347). Add a link to the documentation in the message so users can go and check for more information. 

If the documentation on that is not already written, then we need to write it as part of this issue.

**Comment by ajsantander** [comment]
Addressed by https://github.com/zeppelinos/zos/pull/228
