### ISSUE TITLE
Is it possible to know if contract needs to be created or upgraded ?

### ISSUE THREAD

**Issue by gnoblin** [zeppelinos/zos#27]
To simplify automatic redeployment I mean

So existing contracts get updated and newly added get upgraded

For example I start to develop a dapp with awesome zos and in 1st iteration I have contract A only. I create it. Then I add features to contract A and upgrade it.

But then I add another contract B.

How in my build script can I detect which contact needs which zos commands to be executed during build script?

So that A is just upgraded and B is created as it is first time it is deployed.

Thanks

**Comment by spalladino** [comment]
@gnoblin if you are using the ZeppelinOS CLI, then `zos push` will automatically take care of uploading only the contracts that have changed (internally, the CLI keeps track of contract bytecode hashes, so it only deploys the ones with modifications). Does this work for you?

**Comment by gnoblin** [comment]
but what about create/upgrade commands?

**Comment by spalladino** [comment]
Create will always spin up a new instance (you can have more than one instance of the same contract deployed). As for upgrade, it will only upgrade the instances that are out of date.

**Comment by gnoblin** [comment]
Yes, I understand that. Can this be automated somehow? I mean do I need to code those commands by hand in my build script each time contracts are added/improved?

**Comment by spalladino** [comment]
@gnoblin not sure I follow, but would being able to call the CLI commands from a JS script work for you?

**Comment by facuspagnuolo** [comment]
Closing this issue since there was no answer in the last 24 days. Feel free to open a new issue if necessary.
