### ISSUE TITLE
CLI help for 2.0.x still contains deprecated terminology

### ISSUE THREAD

**Issue by ajsantander** [zeppelinos/zos#272]
### Terminology changes:
stdlib => package
libs => packages

### Examples in commands:
1) `init --link <stdlib>`
2) `init --no-install` | `skip installing stdlib dependencies locally`
3) `init push --deploy-libs`

**Comment by jcarpanelli** [comment]
Fixed [here](https://github.com/zeppelinos/zos/pull/240).
