### ISSUE TITLE
error testing upgradable smart contract in getting started guide

### ISSUE THREAD

**Issue by dogpatchmedia** [zeppelinos/zos#29]
Hi. Im following the directions in the 'getting started guide' and Im on page 2, 'Building an upgradeable application' (https://docs.zeppelinos.org/docs/building.html) and everything goes fine until I get to the bottom where it shows how to test if it was upgraded or not, then I have a problem. The very first line is `myContract = MyContract.at(0x1234567890000000000000) ` every time I put his in, I get:

>  Error: Invalid address passed to MyContract.at()

I see the contract on the local network when i do `truffle networks` or run the `networks` command from in the console. I see the gas money being deducted from my test ETH wallet so I know the contract is working and deployed. I dont understand why its saying that the contracts address is invalid. Its ALWAYS invalid, Ive done this and redone this a 100 times.

**Comment by spalladino** [comment]
Hey @dogpatchmedia! That error seems like you are passing in a malformed address to `MyContract.at`. Are you sure you are passing it as a string, ie enclosed between quotes?

**Comment by facuspagnuolo** [comment]
Closing this issue since there was no answer in the last 22 days and it clearly seems the error was caused by a wrong address.

**Comment by Gargo** [comment]
@facuspagnuolo I have the same issue. Tried a lot of addresses no one works.
Tried twice on different PCs with different operating systems - the result is the same - all main commands from tutorial work but `myContract = MyContract.at(...)` doesn't work

**Comment by facuspagnuolo** [comment]
@Gargo would you mind describing your issue in detail? What is the contract you are working with? which commands are you running? What network are you using?
