### ISSUE TITLE
New CLI command to change admin ownership of a proxy

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos#3]
Add a new command (`transfer`?) to the CLI, that allows delegating ownership of a proxy to another address. 

The command should use the same convention as `update` to indicate which proxy/proxies are to be transferred: _Provide the [alias] you added your contract with, or use --all flag to upgrade all. If no [address] is provided, all instances of that contract class will be upgraded_.

Given that this is a potentially irreversible operation, add a confirmation before executing (but after listing all the proxies that would be transferred). Add support for a `-y/--yes` flag to skip confirmation.

Once the proxy was transferred, add a new attribute `owner` to it in the `zos.network.json` file. All subsequent calls to `update` should skip any proxies with an owner different than the current app.

**Comment by facuspagnuolo** [comment]
Closing it since #47 was already merged
