### ISSUE TITLE
No way to avoid truffle gas price check using the lib in node console

### ISSUE THREAD

**Issue by elopio** [zeppelinos/zos#303]
In a node console, I tried to run the following commands:
```
> var Web3 = require('web3')
> web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:9545"))
> const { Contracts, SimpleProject } = require('zos-lib')
> const MyContract = Contracts.getFromLocal('MyContract')
> myProject = new SimpleProject('MyProject', { from: web3.eth.accounts[0] });
> myProject.createProxy(MyContract)
```
The last step fails saying:
`Error: Cowardly refusing to execute transaction with gas price set to Truffle's default of 100 gwei. Consider explicitly setting a different value in your truffle.js file.`

I changed the gas price on my `truffle.js` before starting truffle `develop`, but the error is the same.
`truffle.js`:
```
module.exports = {
  networks: {
    development: {
      host: 'localhost',
      network_id: '*',
      port: 9545,
      gas: 250000,
      gasPrice: 200000000,
    }
  }
};
```

**Comment by facuspagnuolo** [comment]
Considered fixed on #354 and https://github.com/zeppelinos/zos/pull/359
