### ISSUE TITLE
docs: update all the references to zos.local.json

### ISSUE THREAD

**Issue by elopio** [zeppelinos/zos#321]
On https://github.com/zeppelinos/zos-cli/issues/342, the file zos.local.json was replaced by a file named zos.dev-<network-id>.json, where <network-id> is what we get from `web3.version.getNetwork()` function. It should only appear while working with ganache. For ropsten/kovan/morden/rinkeby zos file names should be `zos.ropsten.json`, `zos.kovan.json`, etc.

We have to replace all the appearances of `zos.local.json`, and we should explain about this on the config files page.

**Comment by ajsantander** [comment]
Fixed by #329
