### ISSUE TITLE
Confusing random bold words in code-blocks of the doc site

### ISSUE THREAD

**Issue by facuspagnuolo** [zeppelinos/zos#340]
Many code blocks of the doc-site present random bold words like:
![image](https://user-images.githubusercontent.com/6967192/47420337-772ba400-d77e-11e8-9a9c-bea69f3640e2.png)

**Comment by elopio** [comment]
This should have been fixed by https://github.com/zeppelinos/zos/pull/336. Are you still seeing bold words @facuspagnuolo ?

**Comment by facuspagnuolo** [comment]
@elopio thanks! marking it as solved!
