### ISSUE TITLE
Improve Solidity syntax highlighting for code blocks

### ISSUE THREAD

**Issue by facuspagnuolo** [zeppelinos/zos#341]
Current Solidity syntax highlighting is too simple, consider using a better one
![image](https://user-images.githubusercontent.com/6967192/47424309-aabefc00-d787-11e8-878c-0f0c546db2c6.png)

**Comment by elopio** [comment]
We can use https://github.com/pospi/highlightjs-solidity. I'm just not sure how to tell docusaurus to use it.

**Comment by facuspagnuolo** [comment]
Thanks for the suggestion @elopio, we can tackle this one after the v2 milestone tho
