### ISSUE TITLE
Publish final v2 version of the docs site

### ISSUE THREAD

**Issue by facuspagnuolo** [zeppelinos/zos#344]

**Comment by jcarpanelli** [comment]
@facuspagnuolo Take into account that `docusaurus` won't let you bump an already created version, but it provides a [version rename script](https://docusaurus.io/docs/en/versioning#renaming-existing-versions) that could be useful. We can rename the current `2.0.0` version to something like `2.0.0-rc.0` and bump to 2.0.0 after that.
