### ISSUE TITLE
Consider renaming stake variable/methods to use 'vouch' instead

### ISSUE THREAD

**Issue by facuspagnuolo** [zeppelinos/zos#350]
The [`Vouching`](https://github.com/zeppelinos/zos/blob/master/packages/vouching/contracts/Vouching.sol) contract uses the word `stake` for some variables and methods. Since we decided [not to use this word anymore](https://github.com/zeppelinos/zos/blob/master/TERMINOLOGY.md) and use the word `vouch` instead, consider renaming the corresponding variables and methods (and their related tests) to follow this decision.

**Comment by vyomshm** [comment]
@facuspagnuolo I'd like to take this on.

**Comment by ajsantander** [comment]
Closing this issue in favor of https://github.com/zeppelinos/zos-vouching/issues/9
