### ISSUE TITLE
Quickstart on the top bar should link to deploying

### ISSUE THREAD

**Issue by elopio** [zeppelinos/zos#372]
My interpretation from Johana's mock ups is that the Quickstart link on the top bar of the docs webiste should link to the first Quickstart guid: Deploying your first project. 

That makes sense to me, however, if I try to update siteConfig.js to say:
```
headerLinks: [
  {
    doc: 'deploying',
    label: 'Quickstart', 
  },
  [...]
```

`npm run build` fails with the following error:
```
(node:31645) UnhandledPromiseRejectionWarning: Error: Processing the following `doc` field in `headerLinks` within `siteConfig.js`: 'deploying'. Check the spe
lling of your `doc` field. If that seems sane, and a document in your docs folder exists with that `id` value,
then this is likely a bug in Docusaurus. Docusaurus thinks one or both of translations (currently set to: false) or versioning (currently set to: true) is ena
bled when maybe they should not be.
Thus my internal id for this doc is: 'version-1.4.0-deploying'. Please file an issue for this possible bug on GitHub.
```

**Comment by elopio** [comment]
@jcarpanelli would you have any idea about this?

**Comment by jcarpanelli** [comment]
@elopio, I deliberately dismissed Yohanna's suggestion because of this error. I believe that docusaurus is complaining because there is no `deploying` section in prior versions, and the `siteConfig.js` file is not versionable (ie, it's a global js config file) :disappointed:.
