### ISSUE TITLE
Error "Cannot find method forEach of undefined" when two contracts with the same name are present in the project

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos#389]
Original title and description:

### Better error message when using oz-eth and oz-sol in the same project

Using oz-eth and oz-sol in the same project is currently unsupported, since any contracts with the same name are compiled into the same artifact (for instance, ERC20.json from oz-sol would overwrite ERC20.json from oz-eth, or the other way around).

However, when this happens, the error the user currently gets is `Cannot find method forEach of undefined`. We should catch this problem earlier, and provider a better error message.

---

Update: this is actually a particular case of a more generic issue. If a project has more than a single contract with the same name (and this includes all the project's dependencies) then this error will occur. We should properly handle all instances of this error, and also check whether it is due to both flavours of openzeppelin installed (and let the user know if that's the case).

**Comment by lsaether** [comment]
Just ran into this problem and was really confused! Glad to find it's an easy fix :+1:
