### ISSUE TITLE
Verify not working

### ISSUE THREAD

**Issue by GarryPlays** [zeppelinos/zos#411]
Error during contract verification: Unable to retrieve the contract creation bytecode.

Trying:
zos verify -n rinkeby Contract

truffle config:
rinkeby: {
      provider: () =>
        new HDWalletProvider(mnemonic, "https://rinkeby.infura.io/", 1),
      gasPrice: 10000000000,
      network_id: '4',
    }

I can deploy on rinkeby and create the proxy, just neither verify the "base" contract manually in etherscan, nor with the verify command whatever that will verify
So how is that supposed to work?

**Comment by mdg92** [comment]
I can replicate this issue in ropsten

**Comment by GarryPlays** [comment]
Oh, I could get it to work at some point. 
First check the solc version you have in your truffle install.
e.g. here: 
`/usr/local/lib/node_modules/truffle/package.json`
which shows something like this
`...`
`"bundleDependencies": false,`
`  "dependencies": {`
`    ...`
`    "solc": "^0.4.15"`
`  },`

Now you know what compiler version you used. Next you have to set it to not optimized. Since the default seems to deploy not optimized. Which is really bad imho.

And voila. Verify works. At least for the none proxy contract.

Of course also flatten the contract, e.g. import the initializer before deploying.

**Comment by GarryPlays** [comment]
And in case someone stumbles upon this, if you add the optimizer to your truffle config it will also deploy the contract optimized. Which really should be in the default config zos init creates.

```
solc: {
    optimizer: {
      enabled: true,
      runs: 200
    }
  }
```

would look similar to this

```
module.exports = {
  networks: {
    local: {
      host: 'localhost',
      port: 8545,
      gas: 5000000,
      gasPrice: 5e9,
      network_id: '*'
    }
  },
  solc: {
    optimizer: {
      enabled: true,
      runs: 200
    }
  }
};
```

**Comment by LewisFreitas** [comment]
How did you manage to `zos verify`? I've been trying it since yesterday and only could verify the logic implementation using etherscan verification tool. 

I would like to have a simple UI for users to interact with methods using e.g. Etherscan. To be able to to that I have to verify the source code of the data instance, right?

**Comment by GarryPlays** [comment]
sadly yes. for that you will need it to be verified. but with zos this will not be possible. Which is really bad, this system needs some rethinking.

I never got the logic itself to verify, but I am assuming it does not show the buttons you want to see. **Please do share the contract address**. Maybe I can at least manually verify mine :D

Now in terms of the contract, I just verified it manually. Make sure to have no "imports" in there, a flattened contract so to speak, and if you didn't add the optimizer I have up there, make sure to set optimized to off (on the etherscan page).
Then it's just hitting the correct compiler version and it should verify fine.

However now you have the buttons, yes, but you can't do anything with it. It will display 0 for everything and you can't interact with it either, since that is done with the logic contract.

**Comment by mdg92** [comment]
Flattening zos contracts is rather hard, since contracts are in multiple folders, and importing them in the correct order is nearly impossible. Having _at least_ a flattener would make it usable
