### ISSUE TITLE
Error: ProviderError: Gas required exceeds allowance or always failing transaction

### ISSUE THREAD

**Issue by patrikdevlin** [zeppelinos/zos#412]
My contract below is always failing when running `zos create Collectibles --init initialize --args Collectible,cc,[0xB1Fe3d2FD237bF06496F61bCFdC032743B07A600],[0xB1Fe3d2FD237bF06496F61bCFdC032743B07A600] -n rinkeby`. The error is `ProviderError: gas required exceeds allowance or always failing transaction`. The logic contract gets deployed fine, but when I use the create function, it will fail. Using a local environment, I do not have the same error.

```
import “zos-lib/contracts/Initializable.sol”;
import “openzeppelin-eth/contracts/token/ERC721/StandaloneERC721.sol”;

contract Collectibles is Initializable, StandaloneERC721 {
    
    function initialize(string name, string symbol, address[] minters, address[] pausers) initializer public {
        StandaloneERC721.initialize(name,symbol,minters,pausers);
    }
}
```

Any help is much appreciated!

**Comment by jeffanthony** [comment]
Just to confirm you do have the proper 'ETH' on each network?

**Comment by patrikdevlin** [comment]
Hi Jeff, Thank you for responding! Yes I do:

https://rinkeby.etherscan.io/address/0x8FF7Cdb0063D5551B80a25c3AdC74B6D088EC1b0 = 3.5 ETH
https://ropsten.etherscan.io/address/0x6Dd675a950E39E0feB7d22a84AdD077A64aD3054 = 6.7 ETH

**Comment by patrikdevlin** [comment]
@jeffanthony Actually I am getting the error if I use made up Private Keys and Mnemoic's...

**Comment by patrikdevlin** [comment]
UPDATE: `zos create Collectibles --network rinkeby` works. However there is a warning that it recognizes the initialize function which needs to be done manually. Trying to figure that out now

**Comment by dimonkov** [comment]
Had the same issue, but with the `zos update`, solved it by adding `--from "address_goes_here"`.

Funny thing is - it already knows the correct address, so if you type in the wrong one - it will give the correct one to you, saying that this is the address of current admin!
However, if you provide nothing - just fails with this meaningless:  
 `ProviderError: gas required exceeds allowance or always failing transaction`.

**Comment by patrikdevlin** [comment]
@dimonkov It seems that that error message is too generic. I solved the issue by changing the contract code in StandaloneERC721. `renounce(this)` was a "always failing transaction".

**Comment by ajsantander** [comment]
@patrikdevlin could you please elaborate on (1) if this issue is solved and (2) if so, what actually solved it?

**Comment by patrikdevlin** [comment]
@ajsantander Of course! 
1. I solved the issue, but not sure if It has been reflected on ZeppelinOS' end. Description is below.

2. It seems that the issue (error message) can occur for many different things. As shown by @dimonkov. I can only speak for the issue that I was dealing with which stemmed from the StandaloneERC721 code. 

`    // Initialize the minter and pauser roles, and renounce them
    ERC721MetadataMintable.initialize(address(this));
    renounceMinter();

    ERC721Pausable.initialize(address(this));
    renouncePauser();
`
When deploying locally on Ganache there is no error. However when deploying to Rinkeby and I believe mainNet this is the source of the problem.  renouncePauser() and renounceMinter() is attempting to renounce the wrong address which causes the transaction to always fail. Thus when you run `zos create ...` it is always failing.

Let me know if you would like me to expand on this any further.

Best,
Pat

**Comment by ConnorChristie** [comment]
I see this has been fixed here: https://github.com/zeppelinos/zos/commit/57f7e3134085ae9cc399fae97c541cc7c9f55a97 but could we get a fix for this in 2.0.0? Perhaps 2.0.2?

**Comment by patrikdevlin** [comment]
@ConnorChristie Where do you see the fix in the commit you mentioned? It is solidity code that is causing the error.

**Comment by ConnorChristie** [comment]
@patrikdevlin The issue has something to do with the way estimate gas is being called for a contract method. That commit I pointed out changes the estimate gas method to use the one on the contract itself

**Comment by jcarpanelli** [comment]
Hey @ConnorChristie, @patrikdevlin sorry for the late response! It seems that this issue was indeed related to the way in which gas was being estimated when calling a contract method. As Connor said, we fixed this in https://github.com/zeppelinos/zos/commit/57f7e3134085ae9cc399fae97c541cc7c9f55a97. 
I'm closing this issue for now, but please do not hesitate on commenting here if you face this problem again.
