### ISSUE TITLE
Contract initialization issue

### ISSUE THREAD

**Issue by medied** [zeppelinos/zos#414]
Similar to #60 but with `zos` version v2. 

Looking at [`create.js`](https://github.com/zeppelinos/zos/blob/master/packages/cli/src/scripts/create.js), it seems the arguments for `createProxy` are still the same so I'd expect `this.proxy = await this.app.createProxy(Vote, 'Vote', 'initialize', [owner]);` to initialize proxy correctly. Could the issue be there? 

Currently deploying on console or running local test both give me an incorrect initialization with a `totalSupply` of 0. 

[Here's the the repo](https://github.com/DemocracyEarth/exodus/blob/master/contracts/token/Vote.sol) to clone and reproduce. I [basically just left](https://github.com/DemocracyEarth/exodus/commit/e52d30e1f42ef0079b8c1fe11a3d0d939f11edc9) variables as `private constant` and add/rename as appropriate to suit `StandaloneERC20.sol`.

**Comment by medied** [comment]
Been diving deeper into docs and [resources online](https://www.youtube.com/watch?v=HU5HdTvwjwg&feature=youtu.be&t=1494) and I'm realizing I'd been thinking about this the wrong way, trying to grasp the EVM packages idea better now.

[This section](https://docs.zeppelinos.org/docs/writing_contracts.html#avoid-initial-values-in-fields-declarations) on avoiding initial values in field declarations made me think of trying the approach below, let's call this approach A: 

```
pragma solidity ^0.4.24;
import "openzeppelin-eth/contracts/token/ERC20/StandaloneERC20.sol";

contract Vote is StandaloneERC20 {
    string public _name;
    string public _symbol;
    uint8 public _decimals;
    uint256 public _INITIAL_SUPPLY;
    address[] _minters;
    address[] _pausers;

    function initialize(address initialAccount) public initializer {
        _name = "Democracy Earth Vote Token";
        _symbol = "VOTE";
        _decimals = 18;
        _INITIAL_SUPPLY = 100000000 * 10**uint256(_decimals);

        StandaloneERC20.initialize(_name, _symbol, _decimals, _INITIAL_SUPPLY, initialAccount, _minters, _pausers);
    }
}
```

But [looking more closely](https://blog.zeppelin.solutions/getting-started-with-openzeppelin-eth-a-new-stable-and-upgradeable-evm-package-576fb37297d0) into EVM packages now in zos v2,  made me realize what could be more powerful is the approach below, call it approach B:

```
pragma solidity ^0.4.24;
import "zos-lib/contracts/Initializable.sol";
import "openzeppelin-eth/contracts/token/ERC20/StandaloneERC20.sol";

contract Vote is Initializable {
    StandaloneERC20 public token;
    
    function initialize(StandaloneERC20 _token) public initializer {
        token = _token;
    }
}
```

Where I then initialize as: 

```
medied$ TOKEN=$(zos create openzeppelin-eth/StandaloneERC20 --args democracyEarth,VOTE,18,100000000000,0x90f8bf6a479f320ead074411a4b0e7944ea8c9c1,[],[])
Using session with network local
Creating proxy to logic contract 0x9561c133dd8580860b6b7e504bc5aa500f0f06a7 and initializing by calling initialize with:
 - name (string): "democracyEarth"
 - symbol (string): "VOTE"
 - decimals (uint8): "18"
 - initialSupply (uint256): "100000000000"
 - initialHolder (address): "0x90f8bf6a479f320ead074411a4b0e7944ea8c9c1"
 - minters (address[]): []
 - pausers (address[]): []
Instance created at 0x2612af3a521c2df9eaf28422ca335b04adf3ac66
Updated zos.dev-1541891459852.json

medied$ echo $TOKEN
0x2612af3a521c2df9eaf28422ca335b04adf3ac66

medied$ zos create Vote --init --args $TOKEN
Using session with network local
Creating proxy to logic contract 0x67b5656d60a809915323bf2c40a8bef15a152e3e and initializing by calling initialize with:
 - _token (address): "0x2612af3a521c2df9eaf28422ca335b04adf3ac66"
Instance created at 0xa57b8a5584442b467b4689f1144d269d096a3daf
0xa57b8a5584442b467b4689f1144d269d096a3daf
Updated zos.dev-1541891459852.json
```

However when I jump to truffle console and interact with contracts with either `myVote.totalSupply()` with approach A or `myVote.token()` with approach B, for example, I keep encountering the revert error `Cannot call fallback function from the proxy admin`. 

What does error mean? After realizing the potential that EVM packages offer looking forward, it seems to me that approach B is the better option. But is there a recommended approach? Mind you the idea is that `Vote.sol` has basic erc20 functionality but specifically set the stage so we can add further functionality to it in the future.

**Comment by medied** [comment]
Just pushed latest changes to reflect/replicate what I'm talking about above, [approach A](https://github.com/DemocracyEarth/exodus/commit/16f9bd5565531dec3877035483848529a0ceca2a) in master and [approach B](https://github.com/DemocracyEarth/exodus/commit/9cd73e125eca1e20c22f678ad603193e403754ef) in separate branch

**Comment by spalladino** [comment]
Hey @medied! Apologies for the delay in the response. As you say, approach B is much more in line with the idea of EVM packages. Instead of redeploying all the code for an ERC20, you rely on an existing implementation provided by `openzeppelin-eth`; you are basically using composability over inheritance.

Regarding the error you are getting, it's most likely caused by the [transparent proxy](https://docs.zeppelinos.org/docs/pattern.html#transparent-proxies-and-function-clashes) approach we are using to prevent the selector clash vulnerability. What it means for you as an end user is that you cannot use the same account for creating/upgrading proxies and for interacting with them. Try using a different ethereum account for querying the contracts!

**Comment by ajsantander** [comment]
@medied, I'm closing this issue, assuming that spalladino's suggestion fixed your problem. Pls, let me know if you are still having the issue tho!
