### ISSUE TITLE
Proposal for transparent proxy initialization and interaction issues

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos#419]
Transparent proxies imply that the address that manages upgradeability in a contract cannot actually interact with it, which is quiteconfusing to most users (see https://github.com/zeppelinos/zos/issues/414 for an example). 

This also causes issues for developers of EVM packages. Contracts that rely on `msg.sender` for setting an `owner` of the contract (for example) in the initializer need to be changed to accept an extra `address` parameter, since the msg.sender is always set to the upgradeability owner of the proxy, and should not match the `owner` (see https://github.com/district0x/memefactory-contracts/issues/1 for an example, or any Ownable contract from openzeppelin).

The first issue implies that we need users to work with two addresses for interacting with their contracts. The easiest solution (which was the default on v1) is to have an externally owned account for interacting with the contracts, and deploy a contract for managing contracts upgrades (the `App`).

As for the second issue, if we want EVM packages developers to be able to freely use `msg.sender`, then the account initializing the contract should be externally owned account, and **not** the App.

---

We can solve both problems by **having the user's account create and initialize all proxies, and then transfer ownership to the App**. This can be compacted into a single transaction by adding an extra `admin` parameter to the proxy constructor:

```solidity
constructor(address _implementation, bytes _data, address _admin)
```

This way, the CLI always uses the user's account for creating new proxies, and provides the App address as the `admin` parameter. As such, **the App is only used for upgrading proxies**, not creating them.

The App is then required for both unpublished and published mode (https://github.com/zeppelinos/zos/issues/291 proposes a lightweight app for unpublished mode). The CLI keeps track of its implementation contracts (or potentially queries a Package in published mode), and then requests the App to upgrade a proxy to a certain address. It is open for discussion whether we want a published-mode App to restrict upgrades to known implementation contracts (instead of to arbitrary addresses), or this should be enforced in a governance layer.

Note that creating proxies directly from an external account has the drawback of slightly more expensive proxy creation (in gas usage), since factories can no longer be used. Should `createProxy` methods be removed from the App, we could provide solidity libraries to facilitate the process of creating proxies from an application smart contract.

Another issue with this approach is that it imposes a difference in the `msg.sender` semantics between initialization and upgrades. If a user wants to rely on `msg.sender` in a `migrate` method, they should be aware that it will be the App and not the user account (as it would be in the `initialize`).

**Comment by frangio** [comment]
I would be okay with the extra `admin` argument in the `Proxy` constructor. I think deployment could be made as cheap as the factory by using `extcodecopy` somehow instead of sending the full bytecode in the transaction.

What about the solution where the `Proxy` itself deploys a ~tiny~ small forwarder contract to act as its "admin"? I like the idea of a new account being created whose exclusive purpose is to manage the proxy. I feel this would fix most issues like the `owner` one you mentioned.

**Comment by rdinicut** [comment]
I am wondering how this would work for an Identity contract considering that there is still a lot of debate around this. 
As far as I understand the user should have 2 accounts, one for owning the identity and one for upgrading it which I think it add some paint points from a UX perspective. Isn't there a way in which the admin can be the owner? 
 Maybe we can have a special method management method on the proxy that you call that always calls the proxy contract all the fallback function always goes to the implementation?

**Comment by spalladino** [comment]
@rdinicut not sure I followed you here:
> Maybe we can have a special management method on the proxy that you call that always calls the proxy contract all the fallback function always goes to the implementation?

That said, this would work with Identity contracts exactly like with external accounts: the identity contract is the (business logic) owner of the proxy, and the owner of an App contract that is the admin of the proxy.

**Comment by rdinicut** [comment]
The idea is the user should own the identity contract but also be able to update the contract. My concerns are related to:
```
require(msg.sender != _admin(), "Cannot call fallback function from the proxy admin");
```
If I understood correctly this is needed in order to know what contract to call: Should I call a method on the proxy or should I delegate to the implementation. 
At the moment If I want to deploy an upgradable Identity. I need 2 contracts(App, Identity) or 2 accounts?

I was thinking that maybe the proxy contract can have flag inAdminMode and a setter in order to remove that constrain the user can be admin and owner at the same time and he can switch between the roles.

**Comment by spalladino** [comment]
> At the moment If I want to deploy an upgradable Identity. I need 2 contracts(App, Identity) or 2 accounts?

You need two addresses. Could be 2 external accounts, or one external account and an App.

> I was thinking that maybe the proxy contract can have flag inAdminMode and a setter in order to remove that constrain the user can be admin and owner at the same time and he can switch between the roles.

The problem then is how to call the setter. If the implementation contract has a method with the same selector as this setter, how do disambiguate?

**Comment by rdinicut** [comment]
reserving a name does not seem such a big trade of IMO

**Comment by spalladino** [comment]
We discussed about this issue offline with @maraoz and @frangio. We agreed on implementing a lightweight version of `App`, to be named `ProxyAdmin`, that acts as an interface of the `upgradeTo`  and `transferAdmin` of the proxy. To signal that the proxy should require having such an admin, we would change the 3rd parameter of the proposed constructor from `address admin` to `ProxyAdmin proxyAdmin`.

We still have the following open problems:

- How to migrate from a ProxyAdmin App to a full-blown App. The options are:
  - Migrate every proxy manually (easiest)
  - Make ProxyAdmin App upgradeable, and compatible with a full App, so we just upgrade
  - Decouple the ProxyAdmin features of the App from those related to Packages management (cleanest)
- How to manage this at the zos-lib level, for users who work directly with the js low-level interface, or even directly with the proxies.
  - We could require zos-lib users to manually their own ProxyAdmins (easiest)
  - Or we could have models like SimpleProject in zos-lib create them if they are not provided
- We are requiring an extra initial transaction on the CLI lightweight mode to create a ProxyAdmin
  - Given it's only one tx, we could very well live with that (easiest)
  - We could deploy Factory contracts (one per network) that are used by the CLI to create both contracts (a proxy and a proxy admin) in a single tx
  - We could have a ProxyWithAdmin contract that extends from Proxy, where the ctor is the only difference, and it creates a ProxyAdmin upon deployment

**Comment by maraoz** [comment]
Awesome. One small nit, I'd continue calling the proxy admin just `ProxyAdmin admin`, not `ProxyAdmin proxyAdmin`.
