### ISSUE TITLE
Design lightweight functions for creating upgradeable instances

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos#42]
Today, using ZeppelinOS involves spinning up an App with Factory, with a Package, with an ImplementationProvider where the implementations are registered, before a proxy can be created. Some users have expressed concern as to locking-in to this structure, and are interested only in using the proxies themselves.

Design a set of functions to just create an upgradeable instance of a contract, without requiring setting up a ZeppelinOS app. Consider integrating these functions with existing frameworks, such as web3 or truffle-contracts.

Derived from https://github.com/zeppelinos/zos/issues/10

**Comment by facuspagnuolo** [comment]
Closing this issue since https://github.com/zeppelinos/zos/pull/59 was already merged
