### ISSUE TITLE
New AdminUpgradeabilityProxy error after upgrading openzepplin-solidity

### ISSUE THREAD

**Issue by nfurfaro** [zeppelinos/zos#423]
I'm attempting to upgrade our project codebase to use a newer version of openzepplin-solidity (Would like to use v2.0.0, Up until now we were using v1.12.0). I only mention openzepplin-solidity for added context. Currently using `"zos-lib": "^2.0.1"`
I've got everything working except for 1 test that is failing with this error:
```
51 passing (19s)
  21 pending
  1 failing

  1) Contract: Unlock
       Proxy Unlock contract
         "before each" hook for "should persist state between upgrades":
     Error: AdminUpgradeabilityProxy error: Please call setProvider() first before calling new().
      at Function.new (node_modules/truffle-contract/contract.js:344:15)
      at Context.<anonymous> (test/Unlock/UnlockProxy.js:17:26)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

The problem seems to be in the `beforeEach()`:
```
const zos = require('zos-lib')
const Unlock = artifacts.require('Unlock')
const UnlockTestV2 = artifacts.require('UnlockTestV2')
const UnlockTestV3 = artifacts.require('UnlockTestV3')
const AdminUpgradeabilityProxy = zos.Contracts.getFromNodeModules('zos-lib', 'AdminUpgradeabilityProxy')
const shared = require('./behaviors/shared')
const Units = require('ethereumjs-units')

contract('Unlock', function (accounts) {
  const proxyAdmin = accounts[1]
  const unlockOwner = accounts[2]

  describe('Proxy Unlock contract', function () {
    beforeEach(async function () {
      const implV1 = await Unlock.new()
      const initV1Call = zos.encodeCall('initialize', ['address'], [unlockOwner])
      this.proxy = await AdminUpgradeabilityProxy.new(implV1.address, initV1Call, { from: proxyAdmin })
      this.unlock = await Unlock.at(this.proxy.address)
    })
```
I'm not the original author of this code. Looking at the `zos` docs I see `createProxy()` being used, but haven't found any reference to using `AdminUpgradeabilityProxy.new()`.

Does this seem like a case of using `zos` incorrectly, or is `AdminUpgradeabilityProxy.new()` the right way to create a new proxy in a testing scenario?

**Comment by facuspagnuolo** [comment]
Hi @nfurfaro! Answering your question:

> Error: AdminUpgradeabilityProxy error: Please call setProvider() first before calling new()
You usually get that error when the web3 provider has not been set to the contract class, in this case, the `AdminUpgradeabilityProxy`. 

> Does this seem like a case of using zos incorrectly, or is AdminUpgradeabilityProxy.new() the right way to create a new proxy in a testing scenario? 
It really depends on what you would like to test. If you are trying to test sth related to how an upgradeable contract should work at a proxy level, I'd go as your example does. OTOH, if you are just creating an upgradeable contract to interact with it, I'd use some of the helper functions provided by zos (see https://github.com/zeppelinos/zos/blob/release/2.1.0/packages/cli/test/models/TestHelper.test.js)

**Comment by facuspagnuolo** [comment]
Closing this issue, feel free to come up with new questions if you have some!
