### ISSUE TITLE
Avoid web3 global variable injection by truffle

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos#430]
We are currently relying on a global web3 instance injected by truffle upon runWithTruffle. Avoid depending on this injection for zos-lib.

**Comment by rdinicut** [comment]
The fact that zos-lib relies on web3 from truffle but has web3 0.2.4 hardcoded apis makes it impossible to write tests in case you are using a newer version of truffle(ex: beta2). 
Is there any workaround for using zos-lib in a truffle, web 1.0 env?

**Comment by spalladino** [comment]
@rdinicut could you ellaborate on the tests you are trying to write, that do not work with zos-lib? We are considering adding new packages that would act as "adapters" for returning truffle contracts from either truffle 4 or 5 (see https://github.com/zeppelinos/zos/issues/447), but that only affects the objects returned by `createProxy` invocations. Would that help?

**Comment by rdinicut** [comment]
I faced problems when trying to deploy the App contract or a proxy using the zos-lib api becasue it relies on https://github.com/zeppelinos/zos/blob/master/packages/lib/src/utils/Transactions.js which has web3 0.20 apis and when I run the tests in a truffle:5.0.0-beta.2 env I get api errors.(then provider is not set, that method does not exit, etc)
So I think the "adapters" will help but you will also need some sort of adapter for the direct web3 api or use your own instance of web3 and use the truffle provider. Maybe something like https://parity-js.github.io/light.js/ might work?
