### ISSUE TITLE
Error when running `zos publish` on existent project using truffle-hdwallet-provider

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos#441]
Issue reported via Slack:

> I got an error when estimating the transaction for setting the version. Turns out that the `from` was missing and therefore it would fail as it requires the `from` to be the owner (for now I just set the from [here](https://github.com/zeppelinos/zos/blob/92fdfd1c9623fea84546c9f650cce0c215d396b9/packages/lib/src/utils/Transactions.js#L135)).
> Because that estimate failed no package/version structure was setup, but since the app and package where deployed the addresses were written to the zos file. Because of that I could not publish that version again.
> Note: we use truffle-hdwallet-provider@0.0.7-beta.1 and set it up in the truffle config with:
> ```
> rinkeby: {
>      provider: () => {
>        return new HDWalletProvider(mnemonic, 'https://rinkeby.infura.io/' + token)
>      },
>      network_id: '4',
>      gasPrice: 25000000000, // 10 Gwei
>    }
> ```

**Comment by jcarpanelli** [comment]
This error shouldn't be reproducible now, as we implemented a function named `estimateActualGasFnCall` that uses `web3` contract's function `estimateGas` method that has the `from` parameter defined (instead of using `web3.eth.estimateGas`) in https://github.com/zeppelinos/zos/pull/310.
