### ISSUE TITLE
Provide support for truffle-contracts on zos-lib exported models

### ISSUE THREAD

**Issue by facuspagnuolo** [zeppelinos/zos#447]
Given that we are about to remove truffle from ZeppelinOS (#428), we should provide a way to support `truffle-contracts` for those exported models that help users building/creating upgradeable smart contracts programmatically. 

A possible solution could be to wrap created contracts with `truffle-contracts` if the user is working on a truffle project.

**Comment by spalladino** [comment]
Consider having two packages: a `zos-lib-truffle-4`, and a `zos-lib-truffle-5`, to support both major versions of truffle.

**Comment by facuspagnuolo** [comment]
Closing, will continue working in #448

**Comment by facuspagnuolo** [comment]
Closing this PR since we already decided to use web3 1.0
