### ISSUE TITLE
UpgradabilityProxy.sol contais outdate OpenZeppelin import

### ISSUE THREAD

**Issue by eshavkun** [zeppelinos/zos#461]
UpgradabilityProxy.sol contains following import:
`import 'openzeppelin-solidity/contracts/AddressUtils.sol';`

Which is outdated when using OpenZeppelin 2.0. It should be:
`import 'openzeppelin-solidity/contracts/utils/Address.sol';`

**Comment by facuspagnuolo** [comment]
Closing in favour of https://github.com/zeppelinos/zos/issues/565
