### ISSUE TITLE
Error "No AST nodes found with ID X" when running validations

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos#465]
> Error: No AST nodes with id 1153 found
>       at StorageLayout.getNode (node_modules/zos-lib/lib/validations/Storage.js:120:32)

This error happens when attempting to run validations on contracts incrementally compiled by truffle. Some background:

The solc compiler produces the AST as well as the bytecode. An incremental numeric ID is assigned to each node in the AST. When compiling all contracts, each node on each contract gets a unique ID: this means that given the ID, we can uniquely identify the node across _all_ contracts.

However, when only a subset of the contracts are compiled (for instance, when truffle detects that some contracts have not changed), the AST node IDs start from 1 once again. This means that an AST node ID may be repeated between a contract in the old compile run and the new one.

We are relying heavily on AST node IDs for running certain checks, especially around storage layout. This issue happens when running these validations with repeated node IDs. The workaround is deleting all compiled contracts, and recompiling them all together from scratch.

We need to figure out a way to avoid this issue entirely for the user.

**Comment by facuspagnuolo** [comment]
Consider handling this error while suggesting to the user to recompile all their contracts
