### ISSUE TITLE
zos commands ignore truffle.js gas setting

### ISSUE THREAD

**Issue by stec0** [zeppelinos/zos#467]
Setup
zos v2.0.1
parity v2.0.1
solidity v0.4.24

Issue
When executing a zos push command, the output is `Transaction Error`

Possible causes
- after investigation, the `this.web3.eth().estimateGas.bind(this.eth())` line in zos-lib's utils Transaction.js fails
- the `if (txParams.gas) {
    return contract.new(...args, txParams)
}` lines in zos-lib's utils Transaction.js are never executed because txParams.gas apperas to never be set. See zos-cli's utils runWithTuffle.js `const txParams = from ? { from: from.toLowerCase() } : {};` where only txParams.from is set. The gas parameter in truffle.js is this ignored.

NB:
- I have not investigated further as to why the estimateGas fails in the first place
- setting txParams.gas by hand in Transactions.js solves the Transaction Error issue
- if you wish, I can propose a fix :)

Thanks!

**Comment by facuspagnuolo** [comment]
Hi @stec0! Thanks for reporting this issue, would you mind providing the exact steps and contracts you were using when you faced this issue? Thanks!
