### ISSUE TITLE
`zos create` silently requires address arguments have all characters in lowercase 

### ISSUE THREAD

**Issue by znss1989** [zeppelinos/zos#501]
I tried to deploy a simple contract as below. 

```
pragma solidity ^0.4.24;

import "openzeppelin-eth/contracts/ownership/Ownable.sol";

contract Foo is Ownable {

    uint256 public x;
    string public s;

    function initialize(uint256 _x, string _s, address _proposedOwner) initializer public {
        Ownable.initialize(_proposedOwner);
        x = _x;
        s = _s;
    }
}
```

After adding proper dependency, I tried to create proxy of it using 

```
zos create Foo --init initialize --args 42,hello,<proposed owner address>
```

However, the `owner` address is always `0x977` no matter what the proposed address is. Later I found that this results from the fact my address argument has character in upper case. 

In my opinion, zos should deal with such case, since it's quite common to have mix cases in address.

**Comment by nfurfaro** [comment]
Same as #421?
