### ISSUE TITLE
Use Web3 1.x types

### ISSUE THREAD

**Issue by ajsantander** [zeppelinos/zos#535]
Web3 v1.x is pretty stable now and should be non-beta soon. We should consider upgrading our Web3 from v0.x to v1.x.

**Related to the Typescript migration**

During the port to Typescript of the lib package, and small experiment was conducted to type web3: #510 
The effort was abandoned because (1) of the proximity of Web3 v1.x, (2) that Web3 v0.x doesn't have official types in the repo nor in DefinitelyTyped, and because (3) looks like Web3 v1.x will offer official types.

During the refactor, @types/web3 should be added ASAP, which should be super helpful for refactoring the code.

**Comment by facuspagnuolo** [comment]
Closing in favour of #563
