### ISSUE TITLE
Docs: "Quickstart" > "Upgrading your project", command returns error 

### ISSUE THREAD

**Issue by sogasg** [zeppelinos/zos#562]
In "Quickstart" > "Upgrading your project", the commands to run in Truffle console to test that things are working as expected returns an error.

The `truffle(local)> myContract.x().toString()` command returns  `myContract.x is not a function`.

A functional tutorial relaying on the web3 ^1.0 implementation instead of TruffleContract to interact with the deployed contracts: https://paulrberg.com/post/2018/12/30/upgradeable-smart-contracts/

**Comment by facuspagnuolo** [comment]
Hi @sogasg! I think you may be using the console of Truffle 5, where the `at` method now returns a promise causing that error. Thanks for reporting it!
