### ISSUE TITLE
Caching of hdwallet provider failing and causing "replacement transaction underpriced" errors

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos#586]
Due to [this issue](https://github.com/trufflesuite/truffle-hdwallet-provider/issues/65#issuecomment-417417192), using a wrapper function that returns an hdwallet-provider in truffle-config fails. To fix that, we had implemented a hack that consisted in evaluating that function to obtain a single instance, and set it as a global provider.

Based on reports from users on zos 2.1.0, truffle 5.0.2, and hdwallet-provider 1.0.2, that is no longer working. Using the wrapper function causes "replacement transaction underpriced" errors, while removing it fixes the issue.

We need to check whether the difference is in zos, truffle, or hdwallet-provider, and re-enable caching the single instance of the provider, since the issue has been open on the provider for over 4 months and there are no signs of fixing.

**Comment by jcarpanelli** [comment]
Do we have more info about this issue? I've tested it with `zos` versions `2.1.0`, `2.1.2` and `2.2.0` but I can't reproduce it neither on testnets (rinkeby, ropsten at least) nor on mainnet :disappointed:.

**Comment by spalladino** [comment]
Reproduced using this truffle config, and pushing a project with 5 contracts:
```
    "rinkeby-infura": {
      provider: () => new HDWalletProvider(mnemonic, "https://rinkeby.infura.io/v3/KEY"),
      network_id: 3
    }
```

**Comment by spalladino** [comment]
Failed to reproduce in 2.2.0. Closing the issue as it seems now fixed.

**Comment by mi-kas** [comment]
I am still experiencing this issue with `zos` version `2.2.1`and `truffle-hdwallet-provider`version `1.0.5`. @spalladino Any ideas how to resolve this?

**Comment by mi-kas** [comment]
@spalladino FYI, after updating truffle from version `4.1.14` to version `5.0.6` the issue doesn't occure anymore.
