### ISSUE TITLE
Use a single version of Web3 in tests

### ISSUE THREAD

**Issue by ajsantander** [zeppelinos/zos#592]
After the migration to Web3 v1, tests are using Web3 v0 (injected by Truffle v4) and zOS is using Web3 v1. The only identifiable incompatibility is that Web3 v0 accounts addresses used in tests need to be checksummed before interacting with Web3 v1, but the thing that really matters is that it may be very confusing to have to deal with two versions of Web3 at all.

As a solution, we may decide to update Truffle to v5, which uses Web3 v1, or not use Truffle in tests at all.

**Comment by spalladino** [comment]
Fixed in https://github.com/zeppelinos/zos/pull/757/commits/fc579c086109eebc28f30cacc89f0f0ac13cef52
