### ISSUE TITLE
Contract not initializing correctly

### ISSUE THREAD

**Issue by medied** [zeppelinos/zos#60]
Setting up a simple contract that inherits from `DetailedPremintedToken`, but `totalSupply` gets incorrectly set to 0. From what I've gathered it seems the issue might be related with how I'm setting the `initialize()` method.

Contract:

```
pragma solidity ^0.4.21;
import "openzeppelin-zos/contracts/token/ERC20/DetailedPremintedToken.sol";

contract DanGrau is DetailedPremintedToken {
    string public name = "Daniel Grau";
    string public symbol = "Grau";
    uint8 public decimals = 4;
    uint256 public INITIAL_SUPPLY = 20000000 * 10**uint256(decimals);

    function initialize(address initialAccount) public isInitializer("DanGrau", "0")  {
        DetailedPremintedToken.initialize(initialAccount, name, symbol, decimals, INITIAL_SUPPLY);
    }
}
```

If I do:

```
$ zos add DanGrau
```
```
$ zos push --deploy-stdlib --network local
```
```
$ zos create DanGrau --init initialize --args <a ganache address> --network local
```

The contract does return variables such as `name` or `symbol` but `totalSupply()` keeps returning 0. And I see the same behavior if I `truffle test`, whether I use the `TestApp()` or interact directly with a `DanGrau` instance.

Could someone expand on [calling initialize() functions manually](https://docs.zeppelinos.org/docs/advanced.html#calling-initialize-functions-manually-in-your-unit-tests)? Not sure if that's where I'm messing up, any pointers will be appreciated

**Comment by spalladino** [comment]
Can you try removing the public modifier from `INITIAL_SUPPLY`, and changing it to a `private constant`? The problem seems to be with how Solidity manages initial values set on fields declarations, as it is equivalent to setting the value in a constructor, which is not supported by zOS.

**Comment by medied** [comment]
Changing `INITIAL_SUPPLY` to a `private constant` gives me a correct `totalSupply` when testing on console (like below) but still a `totalSupply` of 0 when `truffle test`ing (using the `TestApp()` or not)

```
truffle(local)> myContract = Votest.at(<proxy address>)
truffle(local)> myContract.totalSupply()
BigNumber { s: 1, e: 7, c: [ 20000000 ] }
```

Something else you'd recommend me to try beyond the [testing set up](https://docs.zeppelinos.org/docs/testing.html) instructions?

**Comment by spalladino** [comment]
TBH I've had bad experiences with `truffle test` not properly recompiling contracts. Just to be sure, could you clear your build/contracts folder, and rerun the tests? It's odd that it works on the console but not the tests.

**Comment by medied** [comment]
Yea also find it odd that it's working on the console but not the tests, could definitely be related to my setup. Getting the same behavior if I clear `build/contracts`, will try from a fresh directory next. These are the tests I'm running with and without `TestApp()`

```
import {TestApp } from 'zos';

const DanGrau = artifacts.require('DanGrau');

contract('DanGrau', function ([_, owner, recipient, anotherAccount]) {

  beforeEach(async function () {
    this.app = await TestApp({ from: owner })
  });

  describe('via proxy, total supply', function () {
    it('returns the total amount of tokens', async function () {
      const proxy = await this.app.createProxy(DanGrau);
      const result = await proxy.totalSupply();
     
      assert.equal(result.toNumber(), 200000000);
    })
  })

});
```

```
import {TestApp } from 'zos';

const DanGrau = artifacts.require('DanGrau');

contract('DanGrau', function ([_, owner, recipient, anotherAccount]) {

  beforeEach(async function () {
    this.token = await DanGrau.new(owner);
  });

  describe('non-proxy, total supply', function () {
    it('returns the total amount of tokens', async function () {
      const testVar = await this.token.totalSupply();

      assert.equal(testVar.toNumber(), 200000000000);
    });
  });

});
```

**Comment by medied** [comment]
Tried:
- starting from a clean directory, from `zos init` to `zos push`, with [some dependencies added](https://ethereum.stackexchange.com/questions/21210/syntaxerror-unexpected-token-import-on-truffle-test)
- updating truffle from v4.1.11 to v4.1.14

Seeing same behavior though

**Comment by spalladino** [comment]
@medied is the project open source? If so, I can try to clone it and reproduce the issue.

**Comment by medied** [comment]
Attempting to `truffle debug` [results in an error](https://github.com/trufflesuite/truffle-debugger/issues/75#issuecomment-395201651)

**Comment by spalladino** [comment]
Thanks for sharing the code @medied! I cloned the repo and found that the proxy-based test is not initializing the proxy, just creating a new instance. Changing the `createProxy` line to the following does the trick:
```js
const proxy = await this.app.createProxy(Votest, 'Votest', 'initialize', [recipient]);
```

Also, note that if `name`, `symbol`, and `decimals` are flagged as public, they will be zero in the proxy instance (as it happened with `INITIAL_SUPPLY`). Make sure to change them to private constant as well.

**Comment by mi-kas** [comment]
Thanks @spalladino for the clarification! I am now getting always the following error:
```
"before each" hook for "should create a proxy": Error: Release error: Please call setProvider() first before calling new().
```

Any idea how to solve this?

**Comment by spalladino** [comment]
Run your tests with `NODE_ENV=test`

**Comment by medied** [comment]
@spalladino you rock man thanks for all the help, safe to close this issue now 👍

**Comment by spalladino** [comment]
Actually, thank you for helping us figure out all the issues we still need to work on to make our tool more user-friendly! If you stumble upon anything else, please don't hesitate to let us know!
