### ISSUE TITLE
How to initialize new variables when upgrading contracts?

### ISSUE THREAD

**Issue by ZumZoom** [zeppelinos/zos#615]
Consider the following contract:

```solidity
contract A is Initializable {
    uint256 a;

    function initialize() public initializer {
        a = 1;
    }
}
```

A is already deployed to the network along with UpgradeabilityProxy and now I want to upgrade it:

```solidity
contract A is Initializable {
    uint256 a;
    uint256 b;

    function initialize() public initializer {
        a = 1;
        b = 7;
    }
}
```

The problem is that it is not possible to call `initialize` for variable `b` initialization because Proxy's storage was already initialized.

How do I initialize new variables when upgrading contracts using Initializable with UpgradeabilityProxy?

**Comment by spalladino** [comment]
Good idea, thanks!! Just created a new issue to track that. LMK if I can close this one!

**Comment by ZumZoom** [comment]
Sure. Thanks :)
