### ISSUE TITLE
Verify v2.2 contracts source code on Etherscan

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos#627]
See https://forum.zeppelin.solutions/t/evm-with-verified-source-code-on-ropsten/254/6. We should upload an instance of the new ProxyAdmin, as well as the modified Proxy and App contracts, to all networks, and then verify them.

**Comment by jcarpanelli** [comment]
#### Rinkeby:
- **App**: https://rinkeby.etherscan.io/address/0x9a0b2aB904B75De2F0A5bA0576936248A2E64abA#code
- **Package**: https://rinkeby.etherscan.io/address/0xB1CF9f190b6978cd017EfeD85EfE2c9842616CD3#code
- **ImplementationDirectory**: https://rinkeby.etherscan.io/address/0xBFB84Adf04cbbf52eC193fE200e733D136231aA3#code
- **ProxyAdmin**: https://rinkeby.etherscan.io/address/0x91351F575F662aD660f7115404fd66F6dBF26f83#code
- **AdminUpgradeabilityProxy**: https://rinkeby.etherscan.io/address/0xdb0214E7CD5A6B2536F2a78848a18bA97776397F#code

#### Ropsten:
- **App**: https://ropsten.etherscan.io/address/0xC83baA9B81054B3Ca3387803Bd165472e49e9D44#code
- **Package**: https://ropsten.etherscan.io/address/0x402327B2C69C89588AC4aA5dfE5dEC33238f5745#code
- **ImplementationDirectory**: https://ropsten.etherscan.io/address/0xc3503dF28b5f4e74841751782Dfc8Ec20BC651e6#code
- **ProxyAdmin**: https://ropsten.etherscan.io/address/0xA06bc1c0bF3716De90aC06E13F88EF90a3eb7c81#code
- **AdminUpgradeabilityProxy**: https://ropsten.etherscan.io/address/0x2833A938911912322908E9d67891a8c35362f6e7#code

#### Kovan:
- **App**: https://kovan.etherscan.io/address/0x031E3a4c22473f6bA7fBb6e072f918C0e7971321#code
- **Package**: https://kovan.etherscan.io/address/0xa99B87fA80D3CA2784D5206376f62BDb1bEc5FC1#code
- **ImplementationDirectory**: https://kovan.etherscan.io/address/0x97D79F7fA75BE9eB364e65e8962A85d585154471#code
- **ProxyAdmin**: https://kovan.etherscan.io/address/0x00cfD77Fb89432037199857d827BEC887cede17A#code
- **AdminUpgradeabilityProxy**: https://kovan.etherscan.io/address/0x2BD847ebEA6F1D5BeCC9c04214983f3E5774FEe8#code


#### Mainnet:
- **App**: https://etherscan.io/address/0xA4a630C4082F8dd40F1C39913e89BfEFa7882c67#code
- **Package**: https://etherscan.io/address/0x5F6Ac2bFb7FedC4740da55374a521c3A2e1365D4#code
- **ImplementationDirectory**: https://etherscan.io/address/0x84bA79e9d4386cf15c1646467742b1ADBE047062#code
- **ProxyAdmin**: https://etherscan.io/address/0xEcC75A34713Ab1eAba1c69ae3B920C710f69db7F#code
- **AdminUpgradeabilityProxy**: https://etherscan.io/address/0xBAfDD76f3e9AFa61394b04FD37f9BdD3206BdD24#code

**Comment by spalladino** [comment]
Closing as resolved by @jcarpanelli

**Comment by shanefontaine** [comment]
For anyone trying to manually verify the problem with version 2.5.3 of OpenZeppelin (September 2019 ), I was able to verify `InitializableAdminUpgradeabilityProxy.sol` with the following parameters:
* Compiler version: v0.5.3+commit.10d17f24
* Optimization: None
* EVM Version: Default

I used [truffle-flattener](https://www.npmjs.com/package/truffle-flattener) to flatten the contracts directly in my `node_modules`.

You can find the verified contract [here](https://etherscan.io/address/0x02eefd8fd2debc75c52ef1479e56caeaa049ecc7#code).
