### ISSUE TITLE
Links in documentation pointing to source code are broken

### ISSUE THREAD

**Issue by tinchoabbate** [zeppelinos/zos#628]
Many links that intend to point to the actual source code of contracts in the Github repo are broken.

As an example, in https://docs.zeppelinos.org/docs/Initializable.html, the link in _Source: Initializable.sol_ redirects to: `git+https://github.com/zeppelinos/zos/blob/v2.0.1/contracts/Initializable.sol`. 

Removing the `git+` does not fix this issue, since the path to the contract is wrong. In this case, it should be https://github.com/zeppelinos/zos/blob/v2.0.1/packages/lib/contracts/Initializable.sol

**Comment by ajsantander** [comment]
This seems to be a problem with solidity-docgen not prepared to handle multi-package repos like zos: https://github.com/OpenZeppelin/solidity-docgen/blob/master/src/components/document.js#L97

**Comment by ajsantander** [comment]
Submitted a fix for solidity-docgen. As soon as it's merged, updating the dependency and regenerating the docs should fix this issue.
