### ISSUE TITLE
The quickstart guide from the documentation doesn't work with zOS v2.1.x

### ISSUE THREAD

**Issue by ajsantander** [zeppelinos/zos#639]
The quickstart guide, which starts here https://docs.zeppelinos.org/docs/deploying.html is currently experiencing a series of problems due to:
- Transaprent proxy
- Solidity compiler version
- openzeppelin-eth version

We need to make a few adjustments to it so that it works out of the box with zOS v2.1.x

**Comment by spalladino** [comment]
As discussed via chat, let's pin down versions of truffle to 4 (and any other dependencies required) on the guides for 2.1, and then move onto truffle 5 and solidity 0.5 on the guides for 2.2.
