### ISSUE TITLE
Link and unlink commands should not recompile contracts

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos#67]
Running `zos link` or `zos unlink` should not run a recompilation step.

**Comment by jcarpanelli** [comment]
This is *not* the default behaviour. The only way this could happen is by using `zos unlink` or `zos link` with  the `--push` option. Anyways, I'm adding the `--skip-compile` option to be sure there is a manual way of skipping compilation if desired. 
I'm closing this issue, but I'll reference it from a PR.
