### ISSUE TITLE
Add "Cannot call fallback function from the proxy admin" error to FAQ

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos#683]
Calling into a proxy directly from its admin is a common error if the user is using ZeppelinOS programatically and using a SimpleProject, or if they are using just the contract. Let's add an entry to the FAQ explaining what that error means, how to avoid it, and linking to the transparent proxy and proxy admin sections.

**Comment by ajsantander** [comment]
Fixed by #690
