### ISSUE TITLE
Testing guide does not work in v2.2

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos#702]
The `TestHelper` requires ZosContract instances instead of Truffle contract instances to work, and the [testing guide](https://docs.zeppelinos.org/docs/testing.html) instructs to use `artifacts.require` instead of `Contracts.getFromLocal` to load the contract class.

**Comment by ryokomy** [comment]
@spalladino Thanks for making this issue. Do you have any test example which work in v2.2?

**Comment by ryokomy** [comment]
@spalladino Thanks for creating an issue. Do you have any example which work in v2.2.

**Comment by ryokomy** [comment]
I tried test, but the following error occurred.  
`ZWeb3 must be initialized with a web3 provider`

Then, I added
```
const { ZWeb3 } = require('zos-lib')
ZWeb3.initialize("http://localhost:7545")
```
but, another error has come  
`TypeError: Cannot read property 'Contract' of undefined`

**Comment by spalladino** [comment]
Hey @ryokomy! You are correct in that you need to initialize ZWeb3 with either a provider or an URI string. I'm not sure where you are getting the Contract undefined error though, but another problem with the testing guide is that you should be using the contract object from ZeppelinOS instead of from truffle. 

So, your contract class should be set up like:
```js
const MyContract = require('zos-lib').Contracts.getFromLocal('MyContract')
```

Instead of:
```js
const MyContract = artifacts.require('MyContract')
```

**Comment by spalladino** [comment]
I'd suggest looking into the [test file for the TestHelper itself](https://github.com/zeppelinos/zos/blob/master/packages/cli/test/models/TestHelper.test.js) for more info. 

Alternatively, you can just test your contracts as you would do with regular truffle tests, since the proxies don't introduce any difference in their behaviour. Just remember to run `initialize` on your contracts after you have created them!

**Comment by ryokomy** [comment]
@spalladino Thanks for your reply!
It might be the problem only occurred in my environment, but I got `TypeError: Cannot read property 'Contract' of undefined` at `<my project path>/node_modules/zos-lib/src/artifacts/ZWeb3.ts:57:28`.
I think we have compiled javascript file via `npm install`, instead of typescript file.

I also thought maybe solidity 0.5.x was not available, right? My files are written in solidity 0.5.x.

Anyway, thanks for your kind reply!  
I didn't notice that I could use regular truffle tests. I'll write my tests like so for now.

**Comment by spalladino** [comment]
If you're using zOS 2.2 or 2.1, then Solidity 0.5 is fully supported.

As for the issue with the tests, agree on going forward with regular tests.
If you're in the hackathon, look for us tomorrow and we'll help you
troubleshoot the issue. If not, we'd appreciate if you upload your project
so we can try and reproduce your issue. Thanks, and apologies for the
inconvenience!

**Comment by ryokomy** [comment]
I'm using v2.2, so something unexpected happens. 

You mean you're in Tokyo?? That's great, I'm not in the hackathon though. 
I'm now developing our blockchain game using ZeppelinOS. And I migrated it from v2.0 to v2.2.
So I'm happy if we can keep in touch. Thanks!

**Comment by acrdlph** [comment]
I have the same problem.

Even after getting the contract artifacts in the above described way, initializing ZWeb3, deploying the logic contract (`zos push --deploy-dependencies
`) and creating the proxy contract (`zos create MyContract` - I initialize it in the test) I get the error:

```
TypeError: Cannot read property 'Contract' of undefined
```

[Here is the test code](https://github.com/relevant-community/token/blob/UpgradeabilityTests/test/RelevantToken.js) I am working on.

**Comment by spalladino** [comment]
Hey @acrdlph, please check out the fixes that @ajsantander has been working on in this PR: https://github.com/zeppelinos/zos/pull/738. Either way, we will be deploying an updated version of the docsite soon.

**Comment by julien51** [comment]
It looks like the README on the root also needs to be updated...
