### ISSUE TITLE
Interactive prompt to deploy dependencies if they are not present in the current network

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos#707]
If the user is working on a network (such as rinkeby) with an evm package that is not available on that network, then (instead of failing) we should prompt whether they want to deploy that dependency for testing.

If the node is ganache, then deploy anyway without even asking.

**Comment by jcarpanelli** [comment]
I like this :smiley: . As a matter of fact, I would like to avoid failing/throwing in all those cases we are doing so, and prompt a yes-no question instead.
