### ISSUE TITLE
Allow zos commands to run in non-interactive mode

### ISSUE THREAD

**Issue by jcarpanelli** [zeppelinos/zos#729]
Since we are making almost all `zos` commands interactive, we should also take into account those cases in which a non-interactive usage is necessary, for example, when running integration tests or for scripting. 

A good starting point could be @spalladino suggestions [here](https://github.com/zeppelinos/zos/pull/725#pullrequestreview-206859506)

**Comment by spalladino** [comment]
Clearly done!
