### ISSUE TITLE
Once solidity-docgen links are fixed, re-publish the docs

### ISSUE THREAD

**Issue by ajsantander** [zeppelinos/zos#744]
Issue described here https://github.com/zeppelinos/zos/issues/628

This is being resolved in the solidity-docgen repo by either
https://github.com/OpenZeppelin/solidity-docgen/pull/19
or
https://github.com/OpenZeppelin/solidity-docgen/pull/20

Once that is resolved, zos/docs's solidity-docgen dependency needs to be updated, and the documentation needs to be re-published so that the links are fixed.

**Comment by frangio** [comment]
I've published a new version of solidity-docgen with a fix for this. Let me know how it goes!
