### ISSUE TITLE
Error when linking more than a single solidity library to the same contract

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos#751]
Given a contract that uses more than a single _external_ solidity library (ie a library with non-internal functions, that needs to be linked), `zos push` fails to deploy them since linking fails.

The reported error is the following, since `zos` does not check that all pending links have been replaced before deploying (see #250):
```
[Error] Error: Contract deployment failed with error: The data field must be HEX encoded data.
```

This happens because `Contract#link` in `zos-lib` iterates over the set of libraries to replace, but sets the linkedbytecode to the result of replacing the library by its address _on the original bytecode_, and not on the linkedbytecode being accumulated. This causes only the last library to be actually linked.

```typescript
  instance.link = function(libraries: { [libAlias: string]: string }): void {
    Object.keys(libraries).forEach((name: string) => {
      const address = libraries[name].replace(/^0x/, '');
      const regex = new RegExp(`__${name}_+`, 'g');
      instance.schema.linkedBytecode = instance.schema.bytecode.replace(regex, address); // Should be replacing over linkedBytecode, initialized to bytecode!
      instance.schema.linkedDeployedBytecode = instance.schema.deployedBytecode.replace(regex, address); // Same here
    });
  };
```

**Comment by jcarpanelli** [comment]
We may wanto to solve https://github.com/zeppelinos/zos/issues/712 together with this issue.

**Comment by siromivel** [comment]
While the fix here seems trivial I'm having a hard time writing a regression test - do these libraries need to be completely external to the project(e.g., other zos packages)?

**Comment by spalladino** [comment]
> do these libraries need to be completely external to the project (e.g., other zos packages)?

@siromivel not necessarily: any two Solidity libraries in the project will do. The catch is that they must have external methods - a library whose all its functions are internal (such as OZ's SafeMath) does not need to be linked and thus fails to trigger this bug.
