### ISSUE TITLE
Windows spawn ENOENT on truffle compile

### ISSUE THREAD

**Issue by imbenwolf** [zeppelinos/zos#759]
When executing "zos add XY" on Windows 10, I get following error:
`
spawn C:\PATH\TO\PROJECT\node_modules\.bin\truffle ENOENT
`

When replacing line 13 in zos/packages/cli/src/models/compiler/Compiler.ts from:
`
execFile(truffleBin, ['compile', '--all'], (error: ExecException, stdout, stderr) => {
`
to:
``
exec(`${truffleBin} compile --all`, (error: ExecException, stdout, stderr) => {
``
Everything works fine. 

I propose to change this to fix issue on Windows.

**Comment by siromivel** [comment]
I just opened a PR for this - I can't test it in a Windows environment until tomorrow but will update once I do!

**Comment by spalladino** [comment]
Fixed by @siromivel in #764
