### ISSUE TITLE
Filter solidity libraries when prompting contract list

### ISSUE THREAD

**Issue by jcarpanelli** [zeppelinos/zos#760]
When zos prompts the list of contracts when running, for instance, `zos add` or `zos verify`, It should not only filter non-local contracts but solidity libraries as well. 
Consider fixing this issue together with https://github.com/zeppelinos/zos/issues/754.

**Comment by siromivel** [comment]
I can take a look at including this with the PR I have open against #754 this morning, it should be fairly straightforward.
