### ISSUE TITLE
Add goerli to list of known networks

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos#765]
Add Goerli to the [list of known networks](https://github.com/zeppelinos/zos/blob/master/packages/lib/src/artifacts/ZWeb3.ts), and check  whether it is supported by etherscan and etherchain to add it [here](https://github.com/zeppelinos/zos/blob/master/packages/cli/src/models/Verifier.ts) as well.

**Comment by jcarpanelli** [comment]
More info for anyone who wants tackle this issue: Etherscan seems to support it for [contract verification](https://goerli.etherscan.io/verifyContract2), and Infura already included it to their API :slightly_smiling_face:.

**Comment by paulinablaszk** [comment]
Hi, I have added goerli network to these files

**Comment by spalladino** [comment]
Fixed by @paulinablaszk via #768
