### ISSUE TITLE
Typo in function in docs - upgrading

### ISSUE THREAD

**Issue by SamSteele01** [zeppelinos/zos#779]
On the page
`https://docs.zeppelinos.org/docs/upgrading.html`

this function is not correct.
```
  function initializeT(uint256 _t) public {
    require(_t == 0);
    t = _t;
  }
```

The line `require(_t == 0);` means that you can only initialize to the value 0.
Changing to `require(t == 0);`means that you can only initialize once.

**Comment by jcarpanelli** [comment]
Hello @SamSteele01! This issue was tackled in https://github.com/zeppelinos/zos/pull/761/files but it seems that there were other similar typos :disappointed:. Thanks!
