### ISSUE TITLE
Support multiple versions on docsite

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos#8]
The docusaurus documentation site currently displays only the latest version. Given that we are releasing new versions, and have a major release coming soon, we want to keep the historical docs available. We can re-use code from the OZ docsite, which currently does support it.

**Comment by jcarpanelli** [comment]
I'm currently attacking this issue. I think that the current directory structure is a bit annoying, as it has a directory named `docs/` that has a `docs/` directory inside (with the docusaurus scaffold + customisation) and that directory has another `docs/` directory inside (with mds). As this package is only for zos documentation stuff, I think we should merge the `docs/` root directory that contains the `scripts/` folder with the `docs/` directory created by docusaurus.
I'll be opening a new issue proposing this merge so we can discuss it.

```
docs
├── AUTHORS
├── docs
│   ├── docs
│   ├── package.json
│   ├── package-lock.json
│   └── website
│       ├── core
│       ├── i18n
│       ├── package.json
│       ├── package-lock.json
│       ├── pages
│       ├── sidebars.json
│       ├── siteConfig.js
│       ├── static
│       │   ├── css
│       │   └── img
│       └── yarn.lock
├── package.json
├── package-lock.json
├── README.md
├── scripts
│   ├── bump-docs.js
│   ├── gen-docs.js
│   └── util.js
└── yarn.lock
```
