### ISSUE TITLE
Detect initial values in fields declarations and throw a warning

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos#80]
Setting an initial value for a field when declaring it does not work for proxies, since the value is set in the constructor (see https://github.com/zeppelinos/zos/issues/60 and https://github.com/zeppelinos/zos/pull/79 for more info).
```solidity
contract MyContract {
  uint256 public hasInitialValue = 42;
}
```

Note that this is not a problem if the field is defined as `constant`.

We should detect these scenarios, in all contracts (plus their ancestors) and raise a warning. This warning should be run when ~adding~ pushing the contract.

**Comment by vs77bb** [comment]
Hi @spalladino Think I should put up a bounty here / elsewhere with the label? Can do, if you think they're ready 👍

**Comment by spalladino** [comment]
Thanks a lot @vs77bb! We've been shuffling around priorities with @facuspagnuolo during these last few days, so we'll review the `bounty-worthy` labeled issues. We'll be removing the labels from those issues that we plan on tackling internally during the next 6 weeks, and add it to the ones that fell outside of the last planning, but would be nice-to-have nonetheless. We'll keep you posted!
