### ISSUE TITLE
zos create fails with 'out of gas'

### ISSUE THREAD

**Issue by ylv-io** [zeppelinos/zos#816]
While following ZepKit instructions `zos create Counter --init initialize --args 2` command fails with `Returned error: VM Exception while processing transaction: out of gas`
![image](https://user-images.githubusercontent.com/3285000/56395466-60549e80-6243-11e9-88b4-d84ddeb41ab3.png)
![image](https://user-images.githubusercontent.com/3285000/56395482-7a8e7c80-6243-11e9-80b7-cb8a9ff19a68.png)

**Comment by ylv-io** [comment]
After reinstall ZOS, Truffle and Zepkit everything worked.

**Comment by ylv-io** [comment]
igor [7:52 PM]
Okay. I figured out `out of gas` issue (pun intended). It is Ganache. They even say it their release version – https://github.com/trufflesuite/ganache-cli/releases
`A long-standing issue with Ganache has been the fact that we haven't returned EIP-114 compliant gas estimations, AKA the "1/64ths rule". This caused our gas estimates to be too low in cases where a transaction executed opcodes that are subject to this EIP. This in turn was the cause of many frustrations, especially in situations where tools would use gas estimations in transactions without allowing the user to intercept or change the transaction's supplied gas.`
Essentially Ganache would provide wrong estimate. Stick to version `6.3.0` and you’ll be fine. (edited) 
I will pin Ganache version on github repository. We also should pin framework version in tutorial in future. Because as practice shows framework do introduce breaking changes.

**Comment by ejwessel** [comment]
Can confirm
> Stick to version 6.3.0 and you’ll be fine

**Comment by nevverlander** [comment]
Can confirm sticking to 6.3.0 solved my problem too

**Comment by Chrissie** [comment]
Can confirm it too.
If only I knew this earlier, this issue has caused a lot of frustration for me (also in following the ZepKit tutorial).

Maybe include this issue in the documentation?

**Comment by ylv-io** [comment]
Hey @Chrissie ganache-cli version is pinned downed at both https://github.com/zeppelinos/zepkit and https://zepkit.zeppelinos.org/. Do you have something else in mind?

**Comment by Chrissie** [comment]
> Hey @Chrissie ganache-cli version is pinned downed at both https://github.com/zeppelinos/zepkit and https://zepkit.zeppelinos.org/. Do you have something else in mind?

Hi @ylv-io , thanks for your quick response. 

When coming from ZeppelinOS tutorials or projects, you may already have the tools installed and skip that line from the docs.

For example: [https://docs.zeppelinos.org/docs/deploying.html](https://docs.zeppelinos.org/docs/deploying.html) does not mention any CLI version. Maybe add it there too since it is a ZeppelinOS issue, not really a ZepKit one. I would recommend to explicitly mention the bug in higher versions since there will always be stubborn folks like me who always want the latest versions installed.

**Comment by ylv-io** [comment]
@Chrissie, I agree that we should more focus on installing certain versions.
It is not a ZeppelinOS issue per se because it is caused by ganache-cli providing wrong gas estimate.
To be honest we discovered this issue recently and I still hope ganache team would fix it quite soon. Nevertheless I think it is always good idea to pin version in order to receive desired results.
