### ISSUE TITLE
Command for sending an arbitrary tx to a contract

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos#826]
Command should present the user with a list of the proxies they own, and after they pick one, show a list with the public/external non-constant functions of that contract, and then ask for the arguments.

```
zos send-tx --to $CONTRACTADDR --method "foobar"
zos send-tx --to $CONTRACTADDR --args "1,2,3,4" --method "foobar(uint256)" --value 10 --gas 30000
```

**Comment by jcarpanelli** [comment]
Resolved in https://github.com/zeppelinos/zos/pull/848.
