### ISSUE TITLE
Reinstall of zos@2.3.0-rc.0: commands fail with Error: Cannot find module 'simple-git/promise'

### ISSUE THREAD

**Issue by crazyrabbitLTC** [zeppelinos/zos#843]
I'm sure this is some wacky error of my own, but.....

When uninstalling zos (the current version was `2.3.0-alpha.1`) it seems to work. 
Then reinstalling `zos@npm install -g zos@2.3.0-rc.0`  seems to work. 

However after reinstalling, no zos command functions, each fails with:
`Error: Cannot find module 'simple-git/promise'`

Screenshots to show flow: 

Uninstalling, then installing (install console output ommited for brevity):
<img width="974" alt="Screen Shot 2019-05-09 at 8 24 38 AM" src="https://user-images.githubusercontent.com/1938013/57453641-e9546980-7234-11e9-9846-3ea3627e4cdc.png">

Then once finished, trying to execute a `zos session` command. 

<img width="697" alt="Screen Shot 2019-05-09 at 8 25 29 AM" src="https://user-images.githubusercontent.com/1938013/57453691-06893800-7235-11e9-8d27-f738e630d6c5.png">

I must be missing something very obvious here. Have i uninstalled incorrectly?

**Comment by spalladino** [comment]
@crazyrabbitLTC thanks for the report! Indeed there was an issue in how `zos@2.3.0-rc.0` was bundled, which is causing that error. We will be releasing an rc.1 soon, but in the meantime, you can work this around by running `npm install simple-git@1.110.0`.

**Comment by spalladino** [comment]
Fixed in https://github.com/zeppelinos/zos/commit/6ab4bc846014553f475de47c9f423b52db4158f6
