### ISSUE TITLE
Add stricter linter rules

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos#849]
This is an issue to give _carte blanche_ to @ylv-io (I know you want it) for implementing stricter linter rules on the codebase. Let's sync on when to make the change to avoid massive conflicts with other ongoing changes.

**Comment by spalladino** [comment]
FWIW, on #434 Ale had suggested using https://github.com/buzinas/tslint-eslint-rules for linting.

**Comment by ylv-io** [comment]
Yep. My dreams come true. I'll draft code style guidelines and linter rules and after that we all have to agree on them. It is absolutely important to me to make sure everyone happy and agree on the rules.

**Comment by spalladino** [comment]
As long as I get to keep the semicolons, I'm good with pretty much any ruleset

**Comment by spalladino** [comment]
Fixed in #920
