### ISSUE TITLE
Error "A contract alias must be provided to create a new proxy" when creating an instance without compiled contracts

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos#858]
When running `zos create` without having a build/contracts folder, zos prompts to choose one or more contracts. After that, it fails with the error "A contract alias must be provided to create a new proxy".

```
? Select a network from the network list ropsten
Compiling contracts with Truffle...
Compiling ./contracts/Sample.sol...
Compiling zos-lib/contracts/Initializable.sol...
Writing artifacts to ./build/contracts

? Choose one or more contracts AnotherSample, Sample
Adding AnotherSample
Adding Sample
Updated zos.json
A contract alias must be provided to create a new proxy.
```

![Screenshot from 2019-05-13 16-48-31](https://user-images.githubusercontent.com/429604/57649559-f956ab00-759e-11e9-8950-41da696c37dd.png)

**Comment by Medha08** [comment]
I am facing the same issue while initialising the logic contract while linking to the deployed evm package. Can anyone tell me more about this issue and how it can be resolved?

**Comment by spalladino** [comment]
Hey @Medha08! If you are using version `2.3.0-rc.1`, then you should only need to run the command again, or run a `truffle compile`. This issue happens only when you run `zos create` without having any compiled contracts in your project.

Now, if you are using a different version and experiencing this issue, then it's that you need to add a contract name to the command, like `zos create MyContract`.
