### ISSUE TITLE
Do not prompt constant functions to run as initializers

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos#859]
When running `zos create`, the CLI prompts with a list of contract functions to run as initializers. Only non-constant functions should be included in this list. Same for updating.

In the example below, the `version` function is flagged as pure:

![Screenshot from 2019-05-13 16-51-49](https://user-images.githubusercontent.com/429604/57649803-87cb2c80-759f-11e9-90f3-77374f76a00c.png)

@jcarpanelli I'm not sure if this was actually fixed in master as part of another PR. Let me know if that's the case!

**Comment by jcarpanelli** [comment]
This has been solved on https://github.com/zeppelinos/zos/pull/853, We should port that change to the `release/2.3` branch though.

**Comment by spalladino** [comment]
How difficult is it to port it, without bringing in the whole `call` command? If it's not too much effort, could you send a PR aimed at `release/2.3` with it?

**Comment by spalladino** [comment]
Fixed in #879
