### ISSUE TITLE
Automatically push contract if it changed locally

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos#862]
When running `zos create` on a contract that changed (ie source modified and recompiled), the command fails with a "Contract Sample has changed locally since the last deploy, consider running 'zos push'." error. Instead, automatically run `zos push` on behalf of the user (if possible, only on the contract being created).

![Screenshot from 2019-05-13 17-16-04](https://user-images.githubusercontent.com/429604/57651099-d29a7380-75a2-11e9-98be-418081bce30a.png)

To reproduce:
- Write a contract, and compile with `truffle compile`
- Create a new instance via `zos create`
- Modify the contract, and recompile with `truffle compile`
- Create a new instance via `zos create` on the same network

**Comment by jcarpanelli** [comment]
Nice catch! We have two ways of solving this:
1) The super easy way:  Always try to push contracts before creating an instance, as we are doing in https://github.com/zeppelinos/zos/pull/847. I can extend this functionality in the same PR, as it hasn't been merged yet.
2) The no-that-easy way: Isolate logic behind the function that triggers the error and move it to a `util` file.

I would prefer to go with the former, but we can further discuss it and see which one fits better.

**Comment by spalladino** [comment]
Yeah, I'd go with the first option. Could we also make sure that `--skip-compile` can be used as well in both create and update?

**Comment by spalladino** [comment]
Note that the same problem affects `zos update`.
