### ISSUE TITLE
Provide a more descriptive error when running zos unpack in a non-empty directory

### ISSUE THREAD

**Issue by jcarpanelli** [zeppelinos/zos#867]
When runnimg `zos unpack zepkit` in a non-empty directory, zos will throw:
```
jota@zlenovo:~/work/zeppelin/samples/zos-sample$ zos unpack zepkit
The directory must be empty
```

Which I find not very descriptive, and it could be somewhat confusing. We should change it to something like: `Unable to unpack ${kitName} in the current directory, as it must be empty` or something similar.

**Comment by spalladino** [comment]
Fixed by @ylv-io in #869
