### ISSUE TITLE
Interactive commands should have reasonable timeout

### ISSUE THREAD

**Issue by ylv-io** [zeppelinos/zos#871]
If you run any interactive command it will wait forever. This is particularly bad for automated scripts because they will simply stuck without providing any output to figure out what happened.
That happened to me with `Solidity Hot Loader`. Webpack just stuck on message `Starting server...` and that is it.

**Comment by spalladino** [comment]
Not sure I agree with this one, as I'm not sure if this is a common practice for other command line tools. I'd rather spend some time adding a reliable check of [whether the environment is interactive or not](https://unix.stackexchange.com/questions/26676/how-to-check-if-a-shell-is-login-interactive-batch), or just adding an env var to disable interactivity easily.

**Comment by ylv-io** [comment]
Yeah. I like env var approach. I would prefer to take it.

**Comment by spalladino** [comment]
Closing in favour of #874
