### ISSUE TITLE
Broken `zos.json` results to unacceptable output

### ISSUE THREAD

**Issue by ylv-io** [zeppelinos/zos#873]
If `zos.json` is broken output for almost any command will be `Unexpected end of JSON input` which doesn't give user any idea what is wrong. We should change it to something like 'zos.json file is broken, please fix it' or something like that.

![image](https://user-images.githubusercontent.com/3285000/57848166-f1864900-77e0-11e9-99ef-5248b17a4d44.png)

**Comment by spalladino** [comment]
Wonder how you got to this point, but agree that it's a nasty one and should be easy to fix!

**Comment by ylv-io** [comment]
Haha. I edited `zos.json` manually and left some extra comma in json.
