### ISSUE TITLE
Documentation: tutorial using ZeppelinOS 1.x Migratable not clearly marked

### ISSUE THREAD

**Issue by abcoathup** [zeppelinos/zos#923]
Tutorial using ZeppelinOS 1.x Migratable not clearly marked as Migratable has been deprecated in ZeppelinOS 2.x.

Tutorial for ZeppelinOS 1.x:
https://docs.zeppelinos.org/docs/building.html

For new users finding this tutorial, there is no indication that this is for an older version of ZeppelinOS.
(See question in forum: https://forum.zeppelin.solutions/t/could-not-find-zos-lib-contracts-migrations-migratable-sol-from-any-sources-when-following-tutorial/755)

**Comment by spalladino** [comment]
Thanks @abcoathup! I'm closing this one in favor of https://github.com/zeppelinos/zos/issues/917.
