### ISSUE TITLE
Restructure CLI configuration files

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos#931]
With the upcoming [rename](https://github.com/zeppelinos/zos/issues/925), we have the opportunity to rethink how/where the CLI configuration files are set. We have received feedback that **the CLI can be annoying by cluttering the project root with too many files**, such as:
* zos.json
* zos.kovan.json
* zos.mainnet.json
* zos.rinkeby.json
* zos.ropsten.json
* zos.dev-NNNN.json
* .zos.lock
* .zos.session

With this in mind, we can consider moving **all of the files above to a `.openzeppelin` folder**, similar to what `.circleci` does. We can do this along with the renaming defined in #936. The new files should also **handle `manifestVersion` instead of `zosversion`**.

The new `networks.js` file should still be placed the project root, since it's designed to be framework-independent.

We need to define the migration path for this. We can either:
1. Support both of them. If there is a zos.json, use the old structure. If not, use the new one.
2. Automatically move all files to the new structure whenever a command is run, as a migration.

**Comment by crazyrabbitLTC** [comment]
This would simplify a couple of "house keeping" tasks that occasionally come up- the process of removing old zos.<network>.json files from development networks. If you consistently run the same project over and over, you end up with an ever expanding list of a json files in your main project directory.

Would it make any sense to keep build artifacts along side the zos.<network>.json file? The reason being that deploying different version of contracts to different networks is not currently possible as while there can be numerous zos.<network>.json files, there seems like we can only have one build directory. I guess this implies also needing some sort of versioning for the contracts themselves, but perhaps it's worthwhile to keep in mind for the future?
