### ISSUE TITLE
Update zos json files with new CLI lightweight mode

### ISSUE THREAD

**Issue by facuspagnuolo** [zeppelinos/zos#94]
After improving the CLI to work in a lightweight mode by default, the serialization of every project in the `zos.<network>.json` and `zos.json` files may change. We should update its documentation after.

**Comment by spalladino** [comment]
Note that there is already a section in the docs on this (covered [here](https://github.com/zeppelinos/zos-cli/issues/36)). We may want to review it rather than writing one from scratch.

**Comment by facuspagnuolo** [comment]
True, I'll add more details to the description, sorry for that

**Comment by ajsantander** [comment]
Addressed by #222
