### ISSUE TITLE
Random crashes on some data structures

### ISSUE THREAD

**Issue by hickscorp** [zeppelinos/zos#946]
We use ZOS version `2.3.1`, along with ZOS Lib `2.3.1` and some functionality from OpenZeppelin-Solidity `2.3.0`.

The following contract randomly crashes without reason based on the order of calls (Note that it was part of a really much more complex contract set and this is the minimum reproducible example I could come up with that exhibits the bug):

```solidity
pragma solidity ^0.5.0;


contract OrderBook is Initializable {
  enum Status { Pending, Approved, Rejected }

  /// @dev Represents an order, either Pending, Approved or Rejected.
  struct Order {
    address sender;
    address recipient;
    uint256 amount;
    uint256 expiresAt;
    Status status;
  }

  // Per-user order books.
  // mapping (address => Book) private books;
  mapping (address => uint) nextIds;
  mapping (address => mapping (uint => Order)) orders;

  function create(address sender, address recipient, uint amount) public returns (uint) {
    uint id = nextIds[sender];
    // Add the order to the book.
    Order storage order = orders[sender][id];
    order.sender = sender;
    order.recipient = recipient;
    order.amount = amount;
    // Increment nextId for next transfer request.
    nextIds[sender] = id + 1;
    return id;
  }
}
```

Basically, line `nextIds[sender] = id + 1;` crashes with a `revert`. We basically noticed "weird" crashes when starting to have nested storage structs. For example, when we had something like this:

```
struct Book {
  uint256 nextId;
  mapping (uint256 => Order)
}
```

We would be unable to add more than one field into our orders, trying to assign an `order.recipient` would crash. For example:

```solidity
pragma solidity ^0.5.0;
import "../node_modules/zos-lib/contracts/Initializable.sol";


contract OrderBook is Initializable {
  enum Status { Pending, Approved, Rejected }

  /// @dev Represents an order, either Pending, Approved or Rejected.
  struct Order {
    address sender;
    address recipient;
    uint256 amount;
    uint256 expiresAt;
    Status status;
  }

  struct Book {
    uint256 nextId;
    mapping (uint256 => Order) orders;
  }

  // Per-user order books.
  mapping (address => Book) private books;

  function create(address sender, address recipient, uint256 amount) public {
    Book storage book = books[sender];
    mapping (uint256 => Order) storage orders = book.orders;
    Order storage order = orders[book.nextId];
    order.sender = sender;
    // With a slightly different version of the code, it would crash here. But it doesn't anymore.
    order.recipient = recipient;
    order.amount = amount;
    // Uncomenting this line make the code revert().
    // book.nextId = book.nextId + 1;
  }
}
```

It really feels like corruption of the memory - is ZOS ready for prime time? What are we doing wrong?

We discovered that there was most likely an issue with proxied storage when having things in a library like so:

```solidity
pragma solidity ^0.5.0;


library Transferable {
  enum Status { Pending, Approved, Rejected }

  /// @dev Represents an order, either Pending, Approved or Rejected.
  struct Order {
    address sender;
    address recipient;
    uint256 amount;
    uint256 expiresAt;
    Status status;
  }

  /// @dev Represents a group of orders and the index to use for the next one.
  struct Book {
    uint256 nextId;
    mapping (uint256 => Order) orders;
  }

  event Request(address indexed sender, uint256 index);
  event Approval(address indexed sender, uint256 index, string notes);
  event Rejection(address indexed sender, uint256 index, string reason);

  function request(Book storage book, address sender, address recipient, uint256 amount) internal {
    mapping (uint256 => Order) storage orders = book.orders;
    Order storage order = orders[book.nextId];
    order.sender = sender;
    // Un-comment either of the next two lines and a revert() will happen.
    // order.recipient = recipient;
    // order.amount = amount;
    // Event!
    emit Request(sender, book.nextId);
  }
}
```

In our main contract, we have our accounts stored in something like this:

```solidity
  using Transferable for Transferable.Book;

  ...

  struct Account {
    uint256 liquid;
    uint256 frozen;
    Transferable.Book book;
  }

  ...

  // Our accounts are held in this mapping.
  mapping (address => Account) accounts;
```

At some point, we call something like this:

```solidity
    ...
    Account storage senderAccount = accounts[msg.sender];
    senderAccount.book.request(msg.sender, recipient, amount);
```

**Comment by spalladino** [comment]
Hey @hickscorp, thanks for the detailed report. A few more questions to help us diagnose the problem:

- Which version of truffle are you using? [Some versions](https://forum.zeppelin.solutions/t/upgrade-truffle-5-0-13-to-5-0-20/767) have an issue when compiling contracts.
- Are you experiencing these errors with a contract just `create`d via zOS, or after running a `zos update` on it?
- Are you testing in ganache, geth, or parity? Which version?

**Comment by hickscorp** [comment]
@spalladino Thanks for the prompt answer. Here are my comments to your questions:

- We use Truffle at version `5.0.21`, sorry I forgot to mention that.
- We are deploying from scratch and `zos create`'ing our contracts.
- We used a clean Ganache environment as well as a clean PoA Geth chain. The results are inconsistent between the two, but both trigger weird bugs.
- The compiler we use is `0.5.1+commit.c8a2cb62.Emscripten.clang`.

**Comment by hickscorp** [comment]
@spalladino Quick update - I changed most of the code and created truffle migrations that `initialize` the required contracts. The very same problem occurs.
The main difference is that I get an error message (Out of gas).
What's really odd is the fact that there's no chance that such a simple transaction could run out of gas, so I'm not sure whether it could be a `solc` bug or something else...

**Comment by spalladino** [comment]
Well, that rules out a problem with zOS, but I'm still curious as to what the problem may be. How are you sending the transactions that fail? Have you tried manually setting a large gas limit (like 5e6) to see if you still get the out-of-gas?

**Comment by spalladino** [comment]
I'd also consider loading the contracts into remix to debug, to see exactly where the code is reverting.

**Comment by hickscorp** [comment]
@spalladino I've debugged the contracts, and I have no idea what's wrong so far - somehow the `order.sender = ...` and `order.recipient = ...` calls seem to be consuming 20k gas each. Not sure what's happening here.

**Comment by spalladino** [comment]
I'd expect them to cost 20k always when calling `OrderBook#create`, since that's the cost for a sstore on an empty slot. Either way, has manually increasing the gas limit helped?

**Comment by spalladino** [comment]
Closing issue since the error also happens when interacting with contracts directly, bypassing zOS. @hickscorp let us know if you stumble upon any other issues!
