### ISSUE TITLE
How can I extend a contract that is not Migratable and call its constructor?

### ISSUE THREAD

**Issue by YoonjaeYoo** [zeppelinos/zos#95]
I'm writing a contract that is Migratable but not extending a Migratable contract.
See below:

```
contract A {
  uint256 private x;
  constructor(uint256 _x) public {
    x = _x;
  }
}

contract B is A, Migratable {
  function initialize(uint256 _x) isInitializer("B", "0") public {
    x = _x; // error
  }
}
```

There's no way for B to initialize x becuase x is private for A.
Wouldn't there be any way to extend and call super's constructor?

**Comment by spalladino** [comment]
@YoonjaeYoo keep in mind that no contracts in the inheritance chain must have a constructor if you want to work with upgradeable contracts. This means you cannot use A or any contract that extends from B. There is more info on the docs, but we're writing a more detailed guide about this [here](https://github.com/zeppelinos/zos/blob/next/packages/docs/docs/docs/writing_contracts.md). Hope it helps!
