### ISSUE TITLE
zos create Counter fails with not helpful error

### ISSUE THREAD

**Issue by ylv-io** [zeppelinos/zos#950]
![image](https://user-images.githubusercontent.com/3285000/59231568-d1805480-8be9-11e9-89e2-b056235cda2d.png)
Is it a breaking change? Because it used to work at v2.3. I am getting spoiled by interactivity 😄

**Comment by ylv-io** [comment]
Okay. There was a problem with my build folder. Once I deleted it everything started to work. Not sure what was wrong there but some error check for path argument would be good.

**Comment by spalladino** [comment]
> some error check for path argument would be good

Do you know _which_ path failed?

**Comment by ylv-io** [comment]
No. This is the only output I got.

**Comment by spalladino** [comment]
@ylv-io I'm not being able to reproduce, can you dig a bit more deeper?

**Comment by ylv-io** [comment]
Can't reproduce it anymore. I think it was caused by my corrupt build folder. Let's close it for now if it happens again I'll add more details.
