### ISSUE TITLE
ProxyFactory fails to get created proxy address with solidity-coverage

### ISSUE THREAD

**Issue by tsudmi** [zeppelinos/zos#970]
Hi,

### Problem

I receive following error when running tests with `solidity-coverage`:
```bash
TypeError: Cannot read property 'proxy' of undefined
at ProxyFactory.<anonymous> (/zos-lib/src/proxy/ProxyFactory.ts:48:54)
at Generator.next (<anonymous>)
at fulfilled (/zos-lib/lib/proxy/ProxyFactory.js:4:58)
at process._tickCallback (internal/process/next_tick.js:68:7)
```

The problem is that `solidity-coverage` returns Array of two identical elements instead of an Object for the `ProxyCreated` event.

### Environment
- solidity-coverage: `https://github.com:rotcivegaf/solidity-coverage.git#5875f5b7bc74d447f3312c9c0e9fc7814b482477` (The same one used in `openzeppelin-eth`).
- zos-lib: `2.3.1`
- zos-cli: `2.3.1`

### Possible solution

The easy fix would be following:
```javascript
// packages/lib/src/proxy/ProxyFactory.ts
-    const address = events.ProxyCreated.returnValues.proxy;
+    const address = (events.ProxyCreated.returnValues || events.ProxyCreated[0].returnValues).proxy;

```

**Comment by jcarpanelli** [comment]
Hello @tsudmi, thanks for the report and for sharing a possible solution! :+1:

**Comment by tsudmi** [comment]
Hi @jcarpanelli , can I submit a pull request for that?

**Comment by spalladino** [comment]
That would be great, thanks @tsudmi!
