### ISSUE TITLE
Pick compiler info from `zos.json` on `zos verify`

### ISSUE THREAD

**Issue by jcarpanelli** [zeppelinos/zos#986]
The `zos verify` command is picking the compiler info from the `ZosConfig` instead of from the `zos.json` file. This is causing problems when trying to verify a contract against `ethercan`/`etherchain`.

**Comment by spalladino** [comment]
Are we sure that is indeed the issue? Apparently `zos verify` only loads the defaults from the config, but still asks the user to confirm them.

**Comment by jcarpanelli** [comment]
Yeap, but those defaults might not be the same as the ones in the `zos.json`.

**Comment by spalladino** [comment]
Fixed on #1005
