### ISSUE TITLE
zos transfer has some minor output issues

### ISSUE THREAD

**Issue by ylv-io** [zeppelinos/zos#995]
![image](https://user-images.githubusercontent.com/3285000/59717762-5b02d880-9221-11e9-803e-e87d5f2948fc.png)

There is an extra dot after `sent!.` and it says `to send transactions from` but we are sending only one transaction. Are we?

**Comment by jcarpanelli** [comment]
This should be fixed in `v2.4.0-rc.3` Which version are you using?

**Comment by ylv-io** [comment]
I am using latest code from master branch which returns `2.4.0-rc.1`. npm says latest is rc.2. How do I install `rc.3`? From a branch?

**Comment by jcarpanelli** [comment]
I'm sorry, I meant `rc.2` :joy: Master is not up to date with npm though, branch `release/2.4` is.
