### ISSUE TITLE
`zos call` would not list minimal proxies

### ISSUE THREAD

**Issue by ylv-io** [zeppelinos/zos#998]
![image](https://user-images.githubusercontent.com/3285000/59724633-37e12480-9233-11e9-95be-caf17b9e78d3.png)

Is it by design? Still I would want to call method even on minimal proxies.

**Comment by jcarpanelli** [comment]
I believe it is by design, as it's explicitly set in the code. @spalladino may know better though. Is this is a bug, it's super easy to fix.

**Comment by spalladino** [comment]
I'm afraid it's a bug, `zos call` and `zos send-tx` should both accept minimal proxies as well. There is no reason not to.
