### ISSUE TITLE
Passing array arg is to `zos create` is not obvious

### ISSUE THREAD

**Issue by ylv-io** [zeppelinos/zos#999]
![image](https://user-images.githubusercontent.com/3285000/59725581-bbe8db80-9236-11e9-8212-e10368d686b2.png)

I couldn't figure out how to pass array arg to zos create. I've also checked docs and there is no example there.

**Comment by spalladino** [comment]
Besides adding it to the documentation, we should show an example for each data type. @jcarpanelli is there something similar to the grayed-out default in inquirer, but that works as a traditional HTML input placeholder instead of a default?

**Comment by spalladino** [comment]
We could use something like this to show a placeholder given the type:
```js
function getPlaceholder(type: string): string {
  const ARRAY_TYPE_REGEX = /(.+)\[\d*\]$/; // matches array type identifiers like uint[] or byte[4]

  if (type.match(ARRAY_TYPE_REGEX)) {
    const arrayType = type.match(ARRAY_TYPE_REGEX)[1];
    const itemPlaceholder = getPlaceholder(arrayType);
    return `[${itemPlaceholder}, ${itemPlaceholder}]`;
  } else if (
    (type.startsWith('uint') ||
      type.startsWith('int') ||
      type.startsWith('fixed') ||
      type.startsWith('ufixed'))
  ) {
    return '42';
  } else if (type === 'bool') {
    return 'true';
  } else if (type === 'bytes') {
    return '0xabcdef';
  } else if (type === 'address') {
    return '0x1df62f291b2e969fb0849d99d9ce41e2f137006e';
  } else if (type === 'string') {
    return 'Hello world';
  } else {
    return null;
  }
}
```

**Comment by jcarpanelli** [comment]
@spalladino It seems that it's not possible to add a placeholder to an inquirer question. The most similar feature they have is the `default` value, but if the user presses the `enter` key, that default value will be taken as the question's answer.
